### ISSUE TITLE
2024.13.0.190 causes game to unexpectedly freeze on start

### ISSUE THREAD

**Issue by barneschism** [YoYoGames/GameMaker-Bugs#10152]
### Description

Bug package download link:
https://api.gamemaker.io/api/github/downloads/8186090f-ffac-48b2-b4ca-4d5d780f6e49

Upon upgrading from 2024.11.0.179 to 2024.13.0.190, the game now unexpectedly freezes upon load. No changes to the code base have been made since upgrading (beyond the changes GMS makes when upgrading to the newest version).

### Expected Change

It should progress beyond the "setting up" screen that appears when the game is started

### Steps To Reproduce

1. Start GameMaker
4. Game will freeze while loading, with no error messages in the log.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.13.0 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by scott-dunbar** [comment]
Verifed fixed in  IDE v2024.13.1.192  Runtime v2024.13.1.241

**Comment by batblaster** [comment]
Bug still exists also after converting the project with the latest version of the tool.
