### ISSUE TITLE
Bug Reporter: GMRT version is always incorrectly identified as "0.16.0"

### ISSUE THREAD

**Issue by thennothinghappened** [YoYoGames/GameMaker-Bugs#10889]
### Description
I have GMRT 0.17.0 installed (as stated by both the Package Manager, and the package JSON files for GMRT itself), but the Bug Reporter has been writing 0.16.0 as the version for my reports, see #10888 as a test report which exhibits this issue.

### Steps To Reproduce
0. Verify your GMRT version is up-to-date.
1. Open the IDE's Bug Reporter.
2. Select "In-Game (GMRT Runtime)" as the category.
3. Submit the report.
4. Notice that the version reported in the issue differs from your actual installed version.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.13.1.193 Runtime v2024.13.1.242

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[9d6ac093-bac4-473e-a067-faaa4f2c711a](https://api.gamemaker.io/api/github/downloads/9d6ac093-bac4-473e-a067-faaa4f2c711a)

**Comment by mgeddesGM** [comment]
Still occurs as of IDE v2024.1400.5.1047 with GMRT 0.20.11

<img width="599" height="83" alt="Image" src="https://github.com/user-attachments/assets/219eb5c5-ace2-4e47-8b38-a956f5fc67b3" />

This is the same for both "Project Fails to Build (GMRT)" and "In-Game (GMRT)" categories.

**Comment by YYDan** [comment]
Probably one to fix before LTS.

**Comment by YYDan** [comment]
Still occurs in 2026.100 Betas and with all GMRT versions up to internal builds of 22, so have just added to the milestone so we finally fix this.

**Comment by stuckie** [comment]
This should be resolved from 23 onwards

**Comment by alicemoretti** [comment]
This still happens as described on IDE v2026.100.0.1135  Runtime v2026.100.0.1087 using GMRT version 22.44

**Comment by scott-dunbar** [comment]
GMRT version 22.44 - is develop which is 23 btw - yes that is crazy

**Comment by alicemoretti** [comment]
Verified fixed on  IDE v2026.100.0.1152  Runtime v2026.100.0.1101 GMRT 0.23.79. Thank you.
