### ISSUE TITLE
UI/UX: [DPI] [Mac IDE] The IDE becomes oversized after first restart in 2024.1400 Betas, changes despite DPI override being disabled

### ISSUE THREAD

**Issue by sihammill** [YoYoGames/GameMaker-Bugs#11046]
### What Is The Bug?

After installing the latest Beta on macOS Sequoia, the resolution of the IDE is now oversized. DPI override is not enabled.

My display settings are:
Res: 1920 x 1080
GM DPI: No override enabled

### Steps To Reproduce

1. Start GameMaker
2. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1400 (Betas)

### Which operating system(s) are you seeing the problem on?

macOS Sequoia

### Are you running GameMaker from inside your Steam library?

No

### Sample Package

N/A

**Comment by Emc1923** [comment]
On my machine it appears very scaled down, no matter if the DPI override option is enabled or not. 

Specs: MacBook Pro M2 13.3-inch. Built-in Retina display 2560 x 1600 (but with default settings at 1440 x 900). MacOS Sequoia 15.5

**Comment by SmithTom6304** [comment]
If you could also provide the exact IDE version - it may be a duplicate of https://github.com/YoYoGames/GameMaker-Bugs/issues/10986

**Comment by SmithTom6304** [comment]
@sihammill - that issue with the restart sounds like https://github.com/YoYoGames/YoYoStudio/issues/11595, where two versions of GameMaker were being installed side by side on mac.
You should have just the one version of GameMaker Beta installed in `/Applications` - check that you don't also have one installed in `/Users/tom/Applications`. If you do, delete it and remove it from the recycle bin.

You might also want to delete the one in `/Applications` and install the latest beta from https://releases.gamemaker.io/, in case you run into the issue again.

If your GameMaker keeps getting set back to a previous version, [it's likely this issue causing it to display too big](https://github.com/YoYoGames/GameMaker-Bugs/issues/10986)

**Comment by sihammill** [comment]
> [@sihammill](https://github.com/sihammill) - that issue with the restart sounds like [YoYoGames/YoYoStudio#11595](https://github.com/YoYoGames/YoYoStudio/issues/11595), where two versions of GameMaker were being installed side by side on mac. You should have just the one version of GameMaker Beta installed in `/Applications` - check that you don't also have one installed in `/Users/tom/Applications`. If you do, delete it and remove it from the recycle bin.
> 
> You might also want to delete the one in `/Applications` and install the latest beta from https://releases.gamemaker.io/, in case you run into the issue again.
> 
> If your GameMaker keeps getting set back to a previous version, [it's likely this issue causing it to display too big](https://github.com/YoYoGames/GameMaker-Bugs/issues/10986)

I only have one veriosn of GM Beta installed in the `/Applications` directory

**Comment by jonathan-markland** [comment]
Tom did some work recently to account for this different programmatically, with the use of SDL2 and FNA3D API calls to get screen measurements, and from those, calculate an additional ratio for scaling.  Now I can't find the coding ticket.

If a Mac user has been fiddling with the DPI Override percentage in Preferences (in desperation!), then they may come a time where that, and recent code changes like Tom's ratio change, start to fight each other, and Mac users might need to revisit the Preferences, and restore that back to 100% to take it out of the equation.

For all I know, people might be doing this already, but just to clarify!

**Comment by jonathan-markland** [comment]
Maths (as it stands at the time of writing)
----------------------------------------------
The system works on accumulating _scaling factors_. 

Scale factor 1: Account for the DPI Override percentage configured in Preferences: 
- masterDpiOverrideFactor = (DPI Override %age in Preferences) / 100

Scale factor 2: Account for a difference between operating systems:
_The Mac reports 72 units as 1 inch, whereas Windows and Linux report 96 units as 1 inch
This 'OS scale factor' is designed so we never need to consider the Mac again, and just pretend all OS's use 96 == 1 inch._
- osScaleFactor = (Platform.OSType == Platform.macOS) ? (96.0f / 72.0f) : 1.0f;

We then obtain a value the OS is saying the DPI is on the monitor we're interested in, via SDL2:
_(This is where Retina displays talk nonsense, but the next step will account for this)_
- Windowing.GetWindowDPI(WindowDetails, out float hdpi, out float vdpi);     // hdpi is a value like 96 on windows, or 72 on Mac

Scale factor 3: Account for Retina displays talking nonsense to us:
- Windowing.GetSize(WindowDetails, out var drawWidth, out var drawHeight);
- SDL.SDL_GetWindowSize(WindowDetails.Window, out var scaledWidth, out var scaledHeight);
- screenScaleFactor = scaledWidth / drawWidth;    // screenScaleFactor will be1.0 on everything except Retina displays

We then calculate the overall scale factor:
- overall = (hdpi * masterDpiOverrideFactor * osScaleFactor * screenScaleFactor) / 96

Note that while APIs give us separate horizontal vs vertical DPIs, our software cannot handle this, and we only use the horizontal reported values.   This doesn't matter because pixels on everything since IBM CGA/EGA are square.

**Comment by jonathan-markland** [comment]
Steven says:  "We did manage to drill down that that's an SDL2 bug. Potentially fixed in SDL3 but we're not able to update to that to verify, but it seems to be exclusively between internal macbook displays and external mac displays"

(There is pending work on this, as it has been interrupted).

**Comment by sihammill** [comment]
I'm still experiencing this issue in Beta IDE v2024.1400.0.900  Runtime v2024.1400.0.887. I have to currently set the DPI override to 75% just make the screen more viewable.

**Comment by sihammill** [comment]
DPI set at 75%
[09:39:27:900(4174)] Calculated DPI for desktop 1 - Native:(94,95), Scaled:(94,95)

DPI set at 100%
DPI set at 100%[10:46:00:178(b2ff)] Calculated DPI for desktop 1 - Native:(94,95), Scaled:(125,126)

**Comment by SmithTom6304** [comment]
@jonathan-markland That looks to be just the macOS Scaling factor - `(96 / 72) * 94 = 125`
