### ISSUE TITLE
Add extra clarity into the template descriptions/icons for "Blank Game" and "Blank Pixel Game"

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#11057]
### What Is The Bug?

In 2024.13, texture filtering was turned on by default in all projects.

The motivation for this was apparently to encourage people from using GM for visual styles besides pixel art, but any way you look at it what has actually happened is that people think ***GM is bad at pixel art.*** Dealing with blurry sprites are now an obligatory initiation ritual for new users. Complaints about blurry sprites abound on the forum, subreddit, and the Discord, and it now falls on the community to set the record straight. This is not acceptable.

After much to-do in the 1300 betas, a separate "pixel game template project" was added to the start screen (#9638), but this has not helped the situation. The blurry version is the first one on the list of project templates, and [most people just pick the first one on the list when they don't know any better](https://en.wikipedia.org/wiki/Ballot_order_effect).

https://www.reddit.com/r/gamemaker/comments/1lcayxn/how_can_i_fix_the_blurry_screen_in_game_maker/
https://www.reddit.com/r/gamemaker/comments/1koxc7m/blurry_bg_ingame/
https://www.reddit.com/r/gamemaker/comments/1knd99g/how_to_make_games_crisp_on_320x180_game_blurry/
https://www.reddit.com/r/gamemaker/comments/1kl1gj5/blurry_game/
https://www.reddit.com/r/gamemaker/comments/1kkeilm/why_are_my_sprites_blurry/
https://www.reddit.com/r/gamemaker/comments/1kdk99d/blurry_effect_in_the_game/
https://www.reddit.com/r/gamemaker/comments/1j23000/blurry_sprite/
https://www.reddit.com/r/gamemaker/comments/1jvkgkj/blurred_images_after_the_20241300_update/
https://www.reddit.com/r/gamemaker/comments/1jandja/issues_with_pixelated_text_in_gxgames_browser/
https://www.reddit.com/r/gamemaker/comments/1igfkw2/here_to_yap/

https://forum.gamemaker.io/index.php?threads/how-do-i-disable-sprite-anti-aliasing.119962/
https://forum.gamemaker.io/index.php?threads/when-i-scale-up-objects-they-become-blurry.102902/
https://forum.gamemaker.io/index.php?threads/i-have-problems-whit-the-sprites.119327/
https://forum.gamemaker.io/index.php?threads/blurry-sprite-pixel-art.119151/

https://github.com/YoYoGames/GameMaker-Bugs/issues/10942
https://github.com/YoYoGames/GameMaker-Bugs/issues/10607

![Image](https://github.com/user-attachments/assets/5a6ace21-ae21-4284-800c-c32001913c1c)

![Image](https://github.com/user-attachments/assets/10dc9141-e7b6-453d-82df-4b9606785bf2)

![Image](https://github.com/user-attachments/assets/a419a93b-4eba-4edd-9b3f-7931d9c2640b)

![Image](https://github.com/user-attachments/assets/809d7420-1b01-4b66-afc4-bd4b886104da)

![Image](https://github.com/user-attachments/assets/c51b9e79-432a-4c6d-9ed8-9546527cbaae)

![Image](https://github.com/user-attachments/assets/1235a3ca-e265-451a-bff5-602cb9e5a58f)

![Image](https://github.com/user-attachments/assets/3c9d68d2-3c28-4ab0-bbc8-926e7f76cc7c)

![Image](https://github.com/user-attachments/assets/17ec2536-9ba0-4091-a02f-4d15ac800967)

![Image](https://github.com/user-attachments/assets/fbb2331d-cb35-4b4e-b625-56c2a9ad85b3)

![Image](https://github.com/user-attachments/assets/429e4d3e-1259-429a-8208-f83e29e187cf)

![Image](https://github.com/user-attachments/assets/738dd49e-69c3-4ce5-be47-44bbec17fe2f)

![Image](https://github.com/user-attachments/assets/dbae379b-eab8-4d3c-9e4d-64c5e69b0489)

![Image](https://github.com/user-attachments/assets/99e581aa-a3e7-4caf-8148-3e86431c9df5)

This lists of examples is by no means comprehensive.

This has been a problem in the past (mainly with GX, HTML5, and Apple computers) but in the last three months the problem was kicked into high gear since it's now also like this on Windows.

![Image](https://github.com/user-attachments/assets/c89fd292-95b5-4e25-9db3-d354b20e069c)

![Image](https://github.com/user-attachments/assets/788c67f6-c2c0-45c3-a4b1-97e2d54850ee)

![Image](https://github.com/user-attachments/assets/56fdae1b-bcc6-4858-9557-bba1e854aeae)

![Image](https://github.com/user-attachments/assets/4c2ab9b1-511b-45a2-bd5d-594656b2017e)

![Image](https://github.com/user-attachments/assets/4df6d84e-db30-436a-96cd-060985a0f726)

![Image](https://github.com/user-attachments/assets/bf5e6411-1609-41da-8a1e-9369c35b5e5c)

This has become such a problem that the main discord had to make it an FAQ item (and people still ask all the time).

![Image](https://github.com/user-attachments/assets/c70c2c40-7262-4ac4-9284-a8fad410877a)

It's especially bad when people install YYG's own starter material and it looks like this.

https://forum.gamemaker.io/index.php?threads/blurry-sprite.119156/

![Image](https://github.com/user-attachments/assets/c09f5d4a-468e-4bea-9dc0-5cfccbfadc26)

The usual explanation is that texture filtering only affects sprites that are scaled up or down

![Image](https://github.com/user-attachments/assets/b2771a29-d25a-4fd4-89d6-705eb58d5f75)

but the more technical definition is that it affects graphics that aren't drawn to the screen at exactly one texel per pixel of frame buffer, which includes rotation and viewport scaling. It's unrealistic to expect people to have to learn what this means five minutes after they load up GameMaker for the first time. The point of a beginner-friendly engine is to reduce friction in getting people to do what they want to do, not give them something that feels like homework.

Meanwhile, pretty much every pixel art game tutorial on the Internet has you set the window viewport to an integer multiple of the camera size, so this affects pretty much every pixel art game created in 2024.13 and later.

![Image](https://github.com/user-attachments/assets/14f4b696-5163-464a-a23c-6fb946d6feef)

In choosing what the project defaults should be we should also weigh the consequences of making the wrong choice, otherwise known as Pascal's Wager for pixel art:

| | Pixel art | High-resolution art |
| - | - | - |
| Interpolation off | Great | Mildly jaggy |
| Interpolation on | Something is horribly wrong | Great |

[BLANK GAME.zip](https://github.com/user-attachments/files/20767945/BLANK.GAME.zip)

### Expected Change

Disable "interpolate colors between pixels" in default projects

### Steps To Reproduce

1. Go into any of the online GameMaker's communities
2. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.13.1 (Monthly), 2024.1400 (Betas)

### Which platform(s) are you seeing the problem on?

Windows, macOS, Ubuntu, Android, GX.games, HTML5, iOS, PlayStation 4, PlayStation 5, Switch, tvOS, Xbox (GDK)

### Sample Package

attached

**Comment by iampremo** [comment]
This is what the Blank Pixel Game option does

**Comment by tabularelf** [comment]
> This is what the Blank Pixel Game option does

The blank pixel game option is missed a lot more than the average regular iser. Even I've accidentally clicked on it from just pure muscle memory, or just forget that the blank pixel game is there. The icon on it don't really even signify much of anything of what it means, unless you are directly paying attention to the text itself.

For a regular or an experienced user, this isn't the end of the world. But for someone who's just getting started with gamedev, can feel like this is a slap across the face.

**Comment by katsaii** [comment]
This is the first time I'm finding out there is a "Blank Pixel Game" option, I have never noticed it. So I can imagine more inexperienced users just picking the first option anyway.

**Comment by gnysek** [comment]
I also didn't seen "blank pixel game" until someone said it exists.

IMO this should be displayed in same way that GML / GML Visual selection is made (on first run of GM), and user preference should be kept, with info that it can be changed per project + per platform at any moment.

**Comment by ParodyKnaveBob** [comment]
I like gnysek's suggestion.

If the options are going to stay (mostly) as-is on the new project screen, however, I suggest this alternative:
- Swap places. Make the pixel art game the first option instead of second.
- Rename "Blank Game" to "Blank Smooth Art Game" (or something more "opposite" of pixel if you know it).
- Rename "Blank Pixel Game" to "Blank Pixel Art Game" (for simple consistency).
- Maybe even change the pixel art polygons to look more pixely.

Something like this:

![Image](https://github.com/user-attachments/assets/cedcf9c1-0003-4528-a1af-c9c5b6a96fcf)

(I don't intend for "Pixel Art" to look bold compared to other words. Mocked up in Paint. Like with Doc Brown, pardon my lack of scale and all that. Lol.)

This would help establish right from the beginning that there is not *per se* a "[default] Blank Game" plus *some variant* that may or may not get your attention.

**Comment by gnysek** [comment]
Above mockup seems like very good option!

**Comment by rwkay** [comment]
We did things this way so that it is fixed for older IDE versions, we are still working on what will happen with IDE's going forward

1 The icon will be made more Pixel Art (we can push that out across all IDE versions)
2 We are discussing moving the Pixel Art to be the first one (and text changes)
3 The entry dialogs when a project is created is being changed (to support multiple languages JavaScript / C# / GML / GML Visual) so we will look to add a selection on the Pixel Art / Smooth Art to that.

2 and 3 will require an IDE update to happen though, well at least all the plugins update working.

**Comment by tabularelf** [comment]
Bumping... Could we still get the order swapped around?
<img width="490" height="534" alt="Image" src="https://github.com/user-attachments/assets/e175af08-bd72-4d82-aa11-18fb5b738b45" />
