### ISSUE TITLE
In-Game: [Ubuntu, Consoles] Primitive drawing functions are still off-by-one

### ISSUE THREAD

**Issue by nkrapivin** [YoYoGames/GameMaker-Bugs#11062]
### Description
Ditto.
The attached project has 25 testcases that cover almost all the primitive drawing functions, with Windows D3D11 testcase files included.

### Steps To Reproduce
- Start GameMaker
- Try to run the project on consoles
- All testcases should pass

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1400.0.826 Runtime v2024.1400.0.822

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
PlayStation 4, PlayStation 5, Switch, Ubuntu

[18901c53-5c01-4d76-b7ad-29062f80c207](https://api.gamemaker.io/api/github/downloads/18901c53-5c01-4d76-b7ad-29062f80c207)

**Comment by yymrennie** [comment]
Fixed in 2024.14

**Comment by Emc1923** [comment]
For Ubuntu 24.04 some test cases are still failing (0,1,12, etc). Reopening

**Comment by yymrennie** [comment]
Also added is a new option in Game Options->Main Options->General->Deprecated Behaviours called "Legacy primitive drawing behaviour" - this is enabled by default on existing projects but **disabled** on new projects.

This new option, when unchecked, removes all the various offsets that were used to make DirectX 11 primitive drawing match the legacy DirectX 9 primitive drawing behaviour. With this option disabled coordinates are passed straight through unmodified to the underlying graphics API on all platforms in most situations (unfortunately OpenGL-based platforms still require a small vertical offset when drawing primitives to the back buffer (this happens when no surface is set, such as normally during the Draw GUI event) due to maths differences caused by the coordinate system being flipped).

**Comment by yymrennie** [comment]
It seems that the changes that were made help on some OpenGL implementations and not others - it doesn't seem possible to fix this universally across all combinations of hardware and OpenGL drivers. For example, when testing Ubuntu inside a virtual machine different results were obtained when testing with hardware acceleration enabled compared to it disabled.

As can be seen in this FAQ: https://www.opengl.org/archives/resources/faq/technical/rasterization.htm (see "14.090 How do I obtain exact pixelization of lines?") it seems that there's no guarantee that different implementations will draw the same pixels in every scenario.

I'm going to set this to closed again as I suspect the OpenGL part of it is unfixable in a universal way. However, all the other mentioned platforms should now be consistent.

**Comment by Emc1923** [comment]
Closing as per the above comment, thanks.
