### ISSUE TITLE
TestFramework: [VM and YYC] draw_tile in BasicTilemapTestSuite, Trying to remove layer element of unknown type: 65541


### ISSUE THREAD

**Issue by ksuchitra532** [YoYoGames/GameMaker-Bugs#11077]
### Workflow Artifact URL
https://github.com/YoYoGames/GM-TestFramework/actions/runs/15387912598/artifacts/3239581420

### Test Code
```
	// Test for draw_tilemap()
	addTestAsync("draw_tilemap", objTestAsyncDraw, {
		
		ev_create: function() {
			
			var testLayer, layerTilemap;
			
			// Create layer and tilemap for testing, ending the test early if they aren't created successfully
			testLayer = CreateTestLayer();
			if (is_undefined(testLayer)) test_end();
			// Tilemap is set to be 14 tiles wide and 4 tiles high, same as the tileset
			layerTilemap = CreateTestTilemap(testLayer, tilesAuto, 14, 4);
			if (is_undefined(layerTilemap)) test_end();
			
			// Get the amount of tiles in the tileset
			var tilesetInfo = tileset_get_info(tilesAuto);
			var tileCount = tilesetInfo.tile_count;
			// For every tile..
			for (i = 0; i < tileCount; i++)
			{
				// Place them onto the tilemap, as they are arranged on the tileset (14 tiles per row)
				// (i mod 14 increments the x coord every loop until 14, then resets)
				var cell_x = i mod 14;
				// (i div 14 increments the y coord every 14th tile)
				var cell_y = i div 14;
				tilemap_set(layerTilemap, i, cell_x, cell_y);
			}
			
		},
		// This happens every draw event
		ev_draw: function() {
			
			var testLayer, layerTilemap, testSurface, testBuffer, expectedBuffer;
			
			// Find layer and tilemap
			testLayer = layer_get_id("testLayer");
			layerTilemap = layer_tilemap_get_id(testLayer);
			
			// Test that draw_tilemap() draws the tilemap correctly using the draw comparison functions in objTestAsyncDraw:
			// Start drawing to a test surface
			testSurface = start_draw_comparison();
			// draw the tilemap at 0,0
			draw_tilemap(layerTilemap, 0, 0);
			// Stop drawing to the test surface, store it as a buffer, then compare it against the drawTilemapTestExpectedBuffer file
			end_draw_comparison(testSurface, "drawTilemapTest", "draw_tilemap(), failed draw buffer comparison");
			
			// Test draw_tilemap() with invalid args
			TestInvalidArgs(draw_tilemap, 3);
			
			// End test after first draw event
			test_end();
		},
		ev_cleanup: function() {
			
			var testLayer, layerTilemap;
			
			// Find layer and tilemap
			testLayer = layer_get_id("testLayer");
			layerTilemap = layer_tilemap_get_id(testLayer);
			
			// Destroy layer and tilemap
			DestroyTestTilemap(testLayer, layerTilemap);
			DestroyTestLayer(testLayer);
		}
	
	},
```

### Output From The Test
Test Name: draw_tile
Message: Trying to remove layer element of unknown type: 65541

Long Message: ERROR in action number 1
of Draw Event for object objTestAsyncDraw:
Trying to remove layer element of unknown type: 65541

at gml_Script_DestroyTestLayer

Script: gml_Script_DestroyTestLayer

### Runtime Version
2024.1400.0.816

### Location Of The Test
https://github.com/YoYoGames/GM-TestFramework/blob/develop/projects/xUnit/scripts/BasicTilemapTestSuite/BasicTilemapTestSuite.gml#L727-L792

### Which platform(s) are you seeing the problem on?
Windows

**Comment by sihammill** [comment]
TestFramework reports this still fails in [YYC] Runtime Version: 2024.1400.0.826

**Comment by sihammill** [comment]
TestFramework reports this still fails in [YYC] Runtime Version: 2024.1400.0.826

**Comment by jackerley** [comment]
Seems to have passed in 2024.1400.0.827? https://github.com/YoYoGames/GM-TestFramework/actions/runs/15732699719

**Comment by sihammill** [comment]
Verified, test no longer fails in Beta IDE v2024.1400.0.839  Runtime v2024.1400.0.834

**Comment by ksuchitra532** [comment]
TestFramework reports this still fails in [YYC] Runtime Version: 2024.1400.0.838

**Comment by ksuchitra532** [comment]
TestFramework reports this still fails in [YYC] Runtime Version: 2024.1400.0.838

**Comment by sihammill** [comment]
TestFramework reports this still fails in [YYC] Runtime Version: 2024.1400.0.838

**Comment by sihammill** [comment]
TestFramework reports this still fails in [YYC] Runtime Version: 2024.1400.0.838

**Comment by sihammill** [comment]
TestFramework reports this still fails in [YYC] Runtime Version: 2024.1400.0.838

**Comment by sihammill** [comment]
TestFramework reports this still fails in [YYC] Runtime Version: 2024.1400.0.838

**Comment by jackerley** [comment]
Changes have been made to how the test is evaluated, seems to have fixed it for good this time.

**Comment by ksuchitra532** [comment]
TestFramework reports this fails again in [VM and YYC] Runtime Version: 2026.100.0.1039

Title: Sprites asserted to be equal
Description: draw_tile(), failed draw buffer comparison
Actual: null
Expected: null

**Comment by ksuchitra532** [comment]
TestFramework reports this still fails in [VM and YYC] Runtime Version: 2026.100.0.1039

**Comment by jackerley** [comment]
Fixed the testframework to clear the surface it uses for draw comparisons before rendering to them. Should fix this issue.

**Comment by ksuchitra532** [comment]
TestFramework reports this fails again in [VM and YYC] Runtime Version: 2026.100.0.1040

Title: Sprites asserted to be equal
Description: draw_tile(), failed draw buffer comparison
Actual: null
Expected: null

**Comment by ksuchitra532** [comment]
TestFramework reports this still fails in [VM and YYC] Runtime Version: 2026.100.0.1041

**Comment by sihammill** [comment]
TestFramework reports this still fails in [VM and YYC] Runtime Version: 2026.100.0.1040

**Comment by sihammill** [comment]
TestFramework reports this still fails in [VM and YYC] Runtime Version: 2026.100.0.1040

**Comment by sihammill** [comment]
TestFramework reports this still fails in [VM and YYC] Runtime Version: 2026.100.0.1040

**Comment by sihammill** [comment]
TestFramework reports this still fails in [VM and YYC] Runtime Version: 2026.100.0.1040

**Comment by ksuchitra532** [comment]
TestFramework reports this still fails in [VM and YYC] Runtime Version: 2026.100.0.1042

**Comment by ksuchitra532** [comment]
TestFramework reports this still fails in [VM and YYC] Runtime Version: 2026.100.0.1043

**Comment by ksuchitra532** [comment]
TestFramework reports this still fails in [VM and YYC] Runtime Version: 2026.100.0.1044

**Comment by ksuchitra532** [comment]
TestFramework reports this still fails in [VM and YYC] Runtime Version: 2026.100.0.1045

**Comment by ksuchitra532** [comment]
TestFramework reports this still fails in [VM and YYC] Runtime Version: 2026.100.0.1046

**Comment by ksuchitra532** [comment]
TestFramework reports this still fails in [VM and YYC] Runtime Version: 2026.100.0.1047

**Comment by ksuchitra532** [comment]
TestFramework reports this still fails in [VM and YYC] Runtime Version: 2026.100.0.1048

**Comment by ksuchitra532** [comment]
TestFramework reports this still fails in [VM] Runtime Version: 2026.100.0.1049

**Comment by ksuchitra532** [comment]
TestFramework reports this still fails in [VM and YYC] Runtime Version: 2026.100.0.1050

**Comment by ksuchitra532** [comment]
TestFramework reports this still fails in [VM and YYC] Runtime Version: 2026.100.0.1051

**Comment by ksuchitra532** [comment]
TestFramework reports this still fails in [VM and YYC] Runtime Version: 2026.100.0.1052

**Comment by ksuchitra532** [comment]
TestFramework reports this still fails in [VM and YYC] Runtime Version: None

**Comment by sihammill** [comment]
TestFramework reports this still fails in [VM and YYC] Runtime Version: 2026.100.0.1057
