### ISSUE TITLE
Code Editor 2: Breakpoints persist after the line of code is deleted

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#1160]
GM-2193

Bug Type: Bug in the UI or IDE functionality
Ide: 2.3.5.589
Runtime: 2.3.5.458
Os: Windows 10
Components: Debugger

Description: Hello, this is a very minor issue and I'm not entirely sure how to reproduce it. BUT

What I'm running into is a breakpoint at line 87 that persists despite that script asset no longer having 87 lines or a breakpoint marked with the red dot. I had some commented out code in a script that I deleted (tbh not sure when I deleted this, sorry). I think a breakpoint was around there somewhere. At current time, no breakpoints are showing red dots in the code editor. And yet the program stops at the end of the script. I investigated the Breakpoints window and it showed a breakpoint still existing at line 87. I turned it off via this window and the problem is resolved.

**Comment by zreedy** [comment]
Fixed for CE2

**Comment by zreedy** [comment]
Fixed + Merged

**Comment by mgeddesGM** [comment]
issue is still present in  IDE v2024.1100.0.624  Runtime v2024.1100.0.650

1. i made a new project
2. created a script
3. added 11 lines of "show_debug_message("bob")"
4. added break points to lines 8-11
5. i then deleted these lines
6. ran debugger and it stopped on line 7
7. the breakpoints tab still showed break points

i repeated this with a similar project but i ran the project with debugger then reran after deleting the debugger lines
![{57B973B2-8B3D-4D55-9B02-B633C5BED250}](https://github.com/user-attachments/assets/b019e970-cedd-4a60-b725-c5fad4de6178)

**Comment by zreedy** [comment]
It should be noted that the repro above _requires_ that you delete 4 or more contiguous breakpoints otherwise the bug is not observed.

**Comment by zreedy** [comment]
Fixed the remaining edge cases.

**Comment by sihammill** [comment]
Fix verified in IDE v2024.1100.0.646  Runtime v2024.1100.0.666
