### ISSUE TITLE
Debugger: Stepping-into a struct declaration will move the caret to unexpected lines

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GameMaker-Bugs#1747]
### Description
if you create a struct using the debugger and avance using the 
"Step into function call" the cursor will move you to random places.
watch video.

### Steps To Reproduce
1. Create a struct in-line 
2. use the debugger
3. use the "Step into function call" or use F11
4. see how the cursor/screen is move to random places.

[3df1d66e-a6ce-4dd6-a8b7-6345e4913ff7](https://api.gamemaker.io/api/github/downloads/3df1d66e-a6ce-4dd6-a8b7-6345e4913ff7)

**Comment by YYDan** [comment]
Yes, the video shows the code editor jumping up from 1455 to line 206 when the "step into" button is clicked the first time, because _that_ is a line containing a struct declared all on one line.

Clicking it again after that, it does appear to correct itself and step into the function below the struct and work as expected thereafter.

**Comment by rwkay** [comment]
Fixed in 2023.11

**Comment by Totobal5** [comment]
i am on the lates version of the Beta IDE v2023.1100.0.450 Beta Runtime v2023.1100.0.459 and i can confirm that this is still not fixed.
