### ISSUE TITLE
Feather: Search+Replace being used to replace code doesn't automatically refresh the messages window

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#2064]
### Description
When doing global search+replace to replace name of variable or string, Feather won't be updated, thus leading to treat new name as unkwnown function/variable (in scripts/events different that one which defines such thing) until reload of project.
Also, when creating new function/variable with same name as previously replaced, it would report that this function/variable is redeclared.

### Steps To Reproduce
Replace existing function not by renaming/refactoring, but by using global Search & Replace (without opening any resources).

Then open any script/object which calls that function (except script which defines it), and see, that it doesn't know new function. Write function of old name there, and notice, that Feather still keeps it in memory.

[13e72e1d-141f-43a0-8f94-36eaa398b6d1](https://api.gamemaker.io/api/github/downloads/13e72e1d-141f-43a0-8f94-36eaa398b6d1)

**Comment by gnysek** [comment]
If example project or video would be needed, please don't hesitate to let me know.

**Comment by YYDan** [comment]
Suspect the same root issue (or very similar reason) as #2026

**Comment by zreedy** [comment]
Fixed. Code Publisher which is responsible for dispatching notifications for when Find&Replace has made changes to files on disk was not hooked by Feather. Additionally, Code Publisher was not dispatching notifications for changes to in-memory documents.

**Comment by zreedy** [comment]
Cannot reproduce in Red. Probably missed the build window for the previous beta. Please retry with the next one.

**Comment by scott-dunbar** [comment]
Our latest build still shows the second issue listed in the steps above  IDE v2023.1100.0.437  Runtime v2023.1100.0.450

Specifically the statement "Write function of old name there, and notice, that Feather still keeps it in memory."

After renaming the function and then opening the calling script, the autocomplete will still show the old function name

1. Open windy woods (or any project you know the function names of)
2. Open Search and Relace (Ctrl + Shift + F)
3. Set Search as check_collision
4. Set Replace with another name: checkCollisions 
5. Click Replace all
6. Open an event or script that calls the function: obj_enemy_parent: End Step (if using WW for example)
7. Start typing the old function name and observe it is shown in the autocomplete
8. Start typing the new name and observe it is not shown

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/48513045/a74366fa-2cbb-4dc5-a0ac-98d9d750e93c)

**Comment by zreedy** [comment]
Reproduced with the above steps. Fixed now. The File Cache was not being cleared eagerly enough so it was possible that old contents were being reparsed before the cache was refreshed (race condition depending on thread state)

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2023.1100.0.441  Runtime v2023.1100.0.453, thanks.
