### ISSUE TITLE
UI/UX: Find and Replace inside the Code Editor won't close when I press ESC in 2023.1100 Betas

### ISSUE THREAD

**Issue by Koyan61** [YoYoGames/GameMaker-Bugs#2148]
### Description
Inside events find and replace was able be closed via pressing ESC but not in this current beta .435 / .448
Global find and replace ctrl + shift + f is closing when I press ESC but not this event version

### Steps To Reproduce
Open an event
Open find and replace for events via shift + f
Press ESC key

[e826033c-6115-4092-8603-a240c80c2215](https://api.gamemaker.io/api/github/downloads/e826033c-6115-4092-8603-a240c80c2215)

**Comment by SmithTom6304** [comment]
Fixed. Close shortcut hadn't been set up.

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2023.1100.0.439  Runtime v2023.1100.0.452. 

Thank you.

**Comment by Koyan61** [comment]
This still occurs if it loses any way of focus, I cannot close this if I even click on any part of the IDE. It loses focus and cannot close it with ESC If I remember correctly this behavior was not present in previous stables.
![resim_2023-11-18_211836134](https://github.com/YoYoGames/GameMaker-Bugs/assets/90388654/f37c8515-c103-4483-b853-e2d3ddb22b56)
