### ISSUE TITLE
I cannot move objects pixel by pixel in the editor.

### ISSUE THREAD

**Issue by galban83** [YoYoGames/GameMaker-Bugs#2602]
### Description
In the latest update of GMS2, ​​I cannot move objects pixel by pixel in the editor.
 Before I just had to keep the CTRL key pressed, now it doesn't work anymore.

### Steps To Reproduce
Try moving an object in the editor while holding down the CTRL key

[ca469d87-7ba5-4e46-a828-1bef005ab078](https://api.gamemaker.io/api/github/downloads/ca469d87-7ba5-4e46-a828-1bef005ab078)

**Comment by YYDan** [comment]
Hello,

This was fixed in the 11.1 release, so please update your GameMaker when you get chance (your log says you're still using 11.0) and then you should be fine.

You can see that .1's release notes here:
[https://github.com/YoYoGames/GameMaker-Bugs/milestone/9?closed=1](https://github.com/YoYoGames/GameMaker-Bugs/milestone/9?closed=1)

Please always ensure you're on the latest version of GameMaker and you search for existing reports before filing any issues - thanks!

**Comment by galban83** [comment]
Thank you, does this update contain the correction of the underwater effect bug on switch?

https://github.com/YoYoGames/GameMaker-Bugs/issues/2458

**Comment by galban83** [comment]
I just tested, the bug "underwater effect bug on switch" is still present in this new version. I corrected the text file by hand which fixed the problem, and the bug reappeared!
