### ISSUE TITLE
Beta is unable to load any of my projects

### ISSUE THREAD

**Issue by nullbunny** [YoYoGames/GameMaker-Bugs#4582]
### Description
I tried to load any sort of project, from my big main project to small projects I created for tests - all of them make a console pop up for a split second and then it shows me an error message that it cannot load the project

### Steps To Reproduce
Open GameMaker, try to open a project

[ba1f56dc-3ef0-46e6-829d-09d6d676b205](https://api.gamemaker.io/api/github/downloads/ba1f56dc-3ef0-46e6-829d-09d6d676b205)

**Comment by nullbunny** [comment]
Not sure how helpful it will be but I managed to grab a screenshot of the console.

![2024-02-01 10_00_00-Medienwiedergabe](https://github.com/YoYoGames/GameMaker-Bugs/assets/5711400/4a5b8024-6da7-4310-8331-d7350d461ef4)

The project was made with a recent version and contains just a sprite or two and a simple object without any code.

**Comment by stuckie** [comment]
Fixed as part of https://github.com/YoYoGames/ProjectTool/pull/41

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.200.0.483  Runtime v2024.200.0.499

**Comment by nullbunny** [comment]
Still cannot open projects with Beta 4. I opened another issue and attached a project here: #4670
