### ISSUE TITLE
Compile Failure: Final Compile...System.ArgumentException: An item with the same key has already been added. 

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#4599]
### Description
The project fails to compile with the following error:

Error : gml_GlobalScript_RecipeArchives(0) : Fatal Error while compiling - bailing details below
Final Compile...System.ArgumentException: An item with the same key has already been added. Key: GCWeightedField
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at GMAssetCompiler.GMLCompile.FindScriptIndexFromName(GMAssets assets, Dictionary`2& dict, String _name)
   at GMAssetCompiler.GMLCompile.OptimizeVariable(GMLToken _tok, Boolean fLHS, Boolean fPartOfDot)
   at GMAssetCompiler.GMLCompile.OptimizeTree(GMLToken _tok, Boolean fLHS, Boolean fPartOfDot)
   at GMAssetCompiler.GMLCompile.OptimizeTree(GMLToken _tok, Boolean fLHS, Boolean fPartOfDot)
   at GMAssetCompiler.GMLCompile.OptimizeTree(GMLToken _tok, Boolean fLHS, Boolean fPartOfDot)
   at GMAssetCompiler.GMLCompile.OptimizeTree(GMLToken _tok, Boolean fLHS, Boolean fPartOfDot)
   at GMAssetCompiler.GML2VM.Compile(GMAssets _assets, GMLCode _code)

### Steps To Reproduce
1. Run the game in windows VM
2. See the compile failure.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.200.0.481 Runtime v2024.200.0.496

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

[146fc99c-c3a3-4f06-b5b6-2dc758b27095](https://api.gamemaker.io/api/github/downloads/146fc99c-c3a3-4f06-b5b6-2dc758b27095)

**Comment by rwkay** [comment]
Fixed in 2024.2

**Comment by shichen85** [comment]
Just tested runtime 2024.200.0.500, which does not have the fix yet. Will run the test again for the next one!

**Comment by rwkay** [comment]
The fix was added  on Friday night - so 2024.200.0.500 should have the fix in it

**Comment by shichen85** [comment]
Are you testing against the Crashlands-2 project or a different project? 

I just ran in on 2024.200.0.500 and still getting the same error. Attaching the output below:
[output.txt](https://github.com/YoYoGames/GameMaker-Bugs/files/14183141/output.txt)

**Comment by rwkay** [comment]
No I don't seem to have access any longer on Github so I cannot check that directly.

I was getting the same error on an internal project so I was checking that...

I will see if anyone internally has access and I will check.

**Comment by shichen85** [comment]
This ticket was created from the IDE, and I ticked the box to zip the project, so maybe this link has the project? https://api.gamemaker.io/api/github/downloads/146fc99c-c3a3-4f06-b5b6-2dc758b27095

**Comment by rwkay** [comment]
I did not check that bundle... I should have.. apologies

**Comment by rwkay** [comment]
Fixed in 2024.2 - I checked against Crashlands and there was a similar (but different) issue to the one I fixed... the version of Crashlands 2 in the bug did not start properly but crashed out with an error message 

```
Struct.Bschema|13.75| Undefined schema at json path:  
ERROR!!! :: ############################################################################################
ERROR in
action number 1
of  Step Event0
for object o_bschema_loader:


Undefined schema at 
 at gml_Script_bschema_resolve_ref (line 159) - 		show_error("Undefined schema at " + string(json_path), true);
############################################################################################
gml_Script_bschema_resolve_ref (line 159)
gml_Script__bschema_data_hydrate (line 36) - 	schema = bschema_resolve_ref(schema);
gml_Script_bschema_mote_hydrate (line 24) - 	var _hydrated	= _bschema_data_hydrate(_data, _schema, mote_id, _autofill_defaults, true);
gml_Script_colorgrading_hydrate (line 39) - 		var _data = bschema_mote_hydrate(_colorgrade_id);
gml_Script_cl2_hydrate_data (line 21) - 	colorgrading_hydrate();
gml_Script_anon@8974@gc_hydrate_game_data_GameChanger (line 287) - 					return BSCHEMA.project_hydrate() // 1.9 seconds
gml_Script_next@anon@961@DistributedCallbacks_DistributedCallbacks (line 65) -       self.last_value = next_callback(this);
gml_Script_next@anon@961@DistributedCallbacks_DistributedCallbacks (line 58) -       return self.next();
gml_Script_next@anon@961@DistributedCallbacks_DistributedCallbacks (line 58) -       return self.next();
gml_Script_distribute_over_steps (line 131) -   results.next();
gml_Script_gc_hydrate_game_data (line 280) - 			!_fix_motes_before_hydration ? undefined : bschema_fix_all_motes,
gml_Object_o_bschema_loader_Step_0 (line 180) - 			gc_hydrate_game_data(_should_fix_motes, function() { bschema_loader_advance() });
```

Not 100% sure if this indicates another problem or if just a problem with that project.

**Comment by rwkay** [comment]
Fixed in 2024.2 as above.

**Comment by shichen85** [comment]
> Fixed in 2024.2 - I checked against Crashlands and there was a similar (but different) issue to the one I fixed earlier ... the version of Crashlands 2 in the bug did not start properly but crashed out with an error message
> 
> ```
> Struct.Bschema|13.75| Undefined schema at json path:  
> ERROR!!! :: ############################################################################################
> ERROR in
> action number 1
> of  Step Event0
> for object o_bschema_loader:
> 
> 
> Undefined schema at 
>  at gml_Script_bschema_resolve_ref (line 159) - 		show_error("Undefined schema at " + string(json_path), true);
> ############################################################################################
> gml_Script_bschema_resolve_ref (line 159)
> gml_Script__bschema_data_hydrate (line 36) - 	schema = bschema_resolve_ref(schema);
> gml_Script_bschema_mote_hydrate (line 24) - 	var _hydrated	= _bschema_data_hydrate(_data, _schema, mote_id, _autofill_defaults, true);
> gml_Script_colorgrading_hydrate (line 39) - 		var _data = bschema_mote_hydrate(_colorgrade_id);
> gml_Script_cl2_hydrate_data (line 21) - 	colorgrading_hydrate();
> gml_Script_anon@8974@gc_hydrate_game_data_GameChanger (line 287) - 					return BSCHEMA.project_hydrate() // 1.9 seconds
> gml_Script_next@anon@961@DistributedCallbacks_DistributedCallbacks (line 65) -       self.last_value = next_callback(this);
> gml_Script_next@anon@961@DistributedCallbacks_DistributedCallbacks (line 58) -       return self.next();
> gml_Script_next@anon@961@DistributedCallbacks_DistributedCallbacks (line 58) -       return self.next();
> gml_Script_distribute_over_steps (line 131) -   results.next();
> gml_Script_gc_hydrate_game_data (line 280) - 			!_fix_motes_before_hydration ? undefined : bschema_fix_all_motes,
> gml_Object_o_bschema_loader_Step_0 (line 180) - 			gc_hydrate_game_data(_should_fix_motes, function() { bschema_loader_advance() });
> ```
> 
> Not 100% sure if this indicates another problem or if just a problem with that project.

Thanks for the fix. We will look into this once we test against the next runtime.

**Comment by shichen85** [comment]
@rwkay I just tested the project against runtime 2024.200.0.502 and IDE 2024.200.0.486, and I am still getting the same error. Attaching the output below:

[output.txt](https://github.com/YoYoGames/GameMaker-Bugs/files/14194623/output.txt)

**Comment by rwkay** [comment]
Yeah... Fritz did not merge it in fully (he only OK'd the review of the code) - it will be in the next one.

**Comment by caitlinrmcintyre** [comment]
Verified fix for the original error in Beta IDE v2024.200.0.494  Runtime v2024.200.0.511, I am still getting the error that @rwkay posted in the comments above so I recommend filing another issue if you determine that to be a bug also, thanks.
