### ISSUE TITLE
Code Editor 2: Auto complete does not update when assets have been deleted

### ISSUE THREAD

**Issue by sihammill** [YoYoGames/GameMaker-Bugs#5210]
### Description

When an asset has been deleted, the auto complete list continues to display the non-existent assets in the list

![image](https://github.com/YoYoGames/YoYoStudio/assets/101252654/1f22df87-010e-4e35-8f47-45768909d1a6)

### Expected Change

Only assets that exist should appear in the auto complete list

### Steps To Reproduce

1. Start GameMaker
2. Create a project
3. Create and asset
4. Create a script and type the asset name
5. See asset in auto complete list
6. Delete asset
7. Go back to script and type the name of the asset you just delete
8. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta IDE v2024.400.0.526 Beta Runtime v2024.400.0.547

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

None

### ui.log File

- [ ] I have attached my ui.log file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by zreedy** [comment]
Fixed. Cache invalidated and refreshed prior to resource deletion finalization resulting in a stale cache.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1300.0.714  Runtime v2024.1300.0.727

**Comment by mgeddesGM** [comment]
this passes for windows IDE v2024.1300.0.714 Runtime v2024.1300.0.727 but is still an issue in Mac

**Comment by zreedy** [comment]
Fixed on MacOSX. Bug in OmniSharp causes an absolute path to be interpreted as relative which is illegal.
Workaround copied from the `DidCreateFileHandler` solution.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1300.0.768  Runtime v2024.1300.0.775
