### ISSUE TITLE
Code Editor 2: Text highlighting on repeated characters creates a fading effect

### ISSUE THREAD

**Issue by sihammill** [YoYoGames/GameMaker-Bugs#5215]
### Description

This only happen when highlighting characters that are repeated for example:

*****************
or
hhhhhhhhhhhhhh

Highlighting text with mixed characters appears to be fine, see attached video

https://github.com/YoYoGames/YoYoStudio/assets/101252654/2e55e992-7a89-43aa-8e7f-daea348f6672

### Expected Change

Highlighting text with repeated characters should be the same as highlighting text with mixed characters

### Steps To Reproduce

1. Start GameMaker
2. Create an Object/Script
3. Enter a line of text with repeated characters as in the attached video
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

 IDE v2024.400.0.523  Runtime v2024.400.0.544

### Which operating system(s) are you seeing the problem on?

Windows 11, macOS Sonoma

### Are you running GameMaker from inside your Steam library?

None

### ui.log File

- [ ] I have attached my ui.log file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by zreedy** [comment]
Fixed, the occurrence finder was not advancing search offset by the needle length. This should improve performance when selecting text with "Highlight Occurrences" preference enabled.

**Comment by zreedy** [comment]
An additional change to improve the readability of selections has also been completed. A new "Match Highlight" color has been added to Themes, which is different from the "Selection" color. These colors are blended with a `bm_max` mode to improve readability. Change requested as per UI/UX team.

**Comment by sihammill** [comment]
Highlighting repeating characters still doesn't highlight correctly

https://github.com/user-attachments/assets/d246a30a-a27e-406f-8b92-1e97c02496c3

**Comment by zreedy** [comment]
Fixed.

**Comment by sihammill** [comment]
This is still not working correctly, please see the below video.
IDE: Beta IDE v2024.1300.0.722  Runtime v2024.1300.0.735

https://github.com/user-attachments/assets/5b00dde2-b7b0-45f2-bde9-141b1e8a318c

**Comment by zreedy** [comment]
Working as intended however your theme is corrupted. Reset it by deleting all your custom theme files in `%appdata%/GameMaker-Beta/USERNAME/Themes` and restarting the IDE. You may need to also click "Restore Defaults" after this in the Theme settings.

**Comment by sihammill** [comment]
Verified, appears to be fine now in Beta IDE v2024.1300.0.723  Runtime v2024.1300.0.736
