### ISSUE TITLE
Code Editor 2: Auto-Braces Insert Newline in JSDOC (Even with Auto-Braces fully disabled).

### ISSUE THREAD

**Issue by JonathanHackerCG** [YoYoGames/GameMaker-Bugs#5247]
### Description
Starting with a function and JSDOC like this:
```
/// @function draw_sprite_animated
/// @param sprite
```
Inserting an opening brace before the ``sprite`` (to add a type) will add a newline, resulting in this:
```
/// @function draw_sprite_animated
/// @param {
	sprite
```

This happens even if "Auto insert braces" preference is disabled.

### Steps To Reproduce
Write a function, add some JSDOC including some ``@param``. Attempt to insert a JSDOC type with ``{`` and see it adds a newline.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[75469842-4378-410f-8b32-c69d20a622ba](https://api.gamemaker.io/api/github/downloads/75469842-4378-410f-8b32-c69d20a622ba)

**Comment by zreedy** [comment]
Fixed

**Comment by mgeddesGM** [comment]
verified as of IDE v2024.600.0.571  Runtime v2024.600.0.597

**Comment by mgeddesGM** [comment]
still occurring in IDE v2024.600.0.571  Runtime v2024.600.0.597 with the following settings 
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/103565197/3f2eb6d8-4219-46cc-8b10-26a45f671dc7)
![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/103565197/441c6298-3fbc-4262-ac1f-2e6b8299c129)

**Comment by mgeddesGM** [comment]
Auto formatting on { fails on commented lines

**Comment by zreedy** [comment]
The auto formatting issue is now fixed.

**Comment by cameron-home** [comment]
Verified fixed in IDE v2024.800.0.590  Runtime v2024.800.0.614
