### ISSUE TITLE
In-Game: http_request() "result" key value is not populated whenever "http_status" is anything other than a 200 success

### ISSUE THREAD

**Issue by Tom-60** [YoYoGames/GameMaker-Bugs#5287]
### Description

Hi,

We have a REST API setup for our game and when we use the GMS HTTP functions we have unpredictable behaviour. 

Firstly, when we send a login request and it succeeds (status 200), we can retrieve and view the response content without any issues. However, in cases where the login request fails and the server responds with a 400 HTTP status, accessing the response data becomes impossible.

For example, the API returns the login error alongside the 400 response code, so an error response would look like this:
```
{
    "error": "Invalid username/password. Please try again"
}
```

This works as intended and perfectly on a Windows build, however on HTML5 builds it is not possible to view the error content. When showing the message to the user we get 'undefined'. We've also checked and we are unable to access any of the JSON data when the request fails on our HTML build.

Below is the code we are currently running. However, I suspect that the issue lies with GMS itself rather than the specific code we are using.

```
var httpStatus = async_load[? "http_status"];
var jsonResponse = async_load[? "result"];
var responseData = json_decode(jsonResponse);

show_debug_message("HTTP Status: " + string(httpStatus));
show_debug_message("JSON Response: " + jsonResponse);


switch (httpStatus) {
    case 200:
        // User is logged in
        room_goto(home);
        break;
    default:
        var errorMessage = ds_map_find_value(responseData, "error");
        // Show the error message on-screen in red text.
        show_message(errorMessage);
        break;
}
```

### Expected Change

To be able to access JSON data in requests which have failed

### Steps To Reproduce

1. Start GameMaker and open the project in Dan's comment below
2. Run the project for any target
3. Observe on Windows you will get an in-game code error shown because the result key is still "undefined" / on HTML5 you will get a CORS error
4. See the map key is still undefined

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)
2024.13.1
2024.1400 Beta 6

### Which operating system(s) are you seeing the problem on?

Windows 11, Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [ ] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by DiasFranciscoA** [comment]
The issue has been resolved. Previously, only HTTP responses with success status codes were successfully reaching the runner.

**Comment by mgeddesGM** [comment]
verified by developer for IDE v2024.4.0.137 Runtime v2024.4.0.168

**Comment by YYDan** [comment]
IDE v2024.1400.0.841  Runtime v2024.1400.0.836 still shows this leaves the key as "undefined". Have removed the HTML5-specific bit from the title, as all platforms are the same.

A sample project added now also : [httpTest.zip](https://github.com/user-attachments/files/21018312/httpTest.zip)
