### ISSUE TITLE
Code Editor 2: Split code views and "Show all documents in single view" disabled only ever sets the event correctly for the first view

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#5392]
### Description
The event selection menu only ever changes the main view, which means that if you have "show all documents in single view" disabled, there's no way to change the event that a split view is focused on. Since the split always defaults to the first event (create in this case), I can't get it to show step or draw.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/8975dc24-db9f-412a-a176-749e6944b700

### Steps To Reproduce
Disable "show all documents in single view", and then split your code view. Try to change the event of the split view.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.532 Runtime v2024.400.0.551

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[00fb5036-fbeb-480e-bfdf-903220015ee9](https://api.gamemaker.io/api/github/downloads/00fb5036-fbeb-480e-bfdf-903220015ee9)

**Comment by zreedy** [comment]
Fixed. Required an extensive refactor to move elements of the `DocumentWindow` into `DocumentWorkspace` with an exposure of all windows open.

**Comment by Emc1923** [comment]
Issue remains as of  IDE v2024.800.0.603  Runtime v2024.800.0.625, reopening. Thanks.

**Comment by zreedy** [comment]
There was an accidental regression while fixing another related bug in the same PR.
This regression is now fixed, pending merge.

**Comment by zreedy** [comment]
Fixed + Merged

**Comment by caitlinrmcintyre** [comment]
Verified fix in  IDE v2024.1000.0.621  Runtime v2024.1000.0.647, thanks.
