### ISSUE TITLE
UI/UX: Shortcuts that use modifier keys are not being registered properly

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#5417]
### Description

When trying to use a shortcut that includes any modifier key (e.g. Shift, Ctrl) these are not registered. They also appear listed in the IDE with extra '+' symbols:

![image](https://github.com/YoYoGames/YoYoStudio/assets/105791928/7019f870-ce3a-488d-bf3d-825364188a79)
![image](https://github.com/YoYoGames/YoYoStudio/assets/105791928/c321e0dd-6ed6-4c16-a172-7743a62b1669)
![image](https://github.com/YoYoGames/YoYoStudio/assets/105791928/56876046-855c-46e4-9f09-99bc723a30cf)
...

The following message can be also observed in the ui.log:

```
[16:18:44:733(17f9)] Error deserializing Hotkeys in file './default_hotkeys.json' - Key entry Shift is not a valid Key
[16:18:44:734(17f9)] Error deserializing Hotkeys in file './default_hotkeys.json' - Key entry Control is not a valid Key
[16:18:44:734(17f9)] Error deserializing Hotkeys in file './default_hotkeys.json' - Key entry Shift is not a valid Key
[16:18:44:735(17f9)] Error deserializing Hotkeys in file './default_hotkeys.json' - Key entry Control is not a valid Key
[16:18:44:735(17f9)] Error deserializing Hotkeys in file './default_hotkeys.json' - Key entry Shift is not a valid Key
```
[ui.log](https://github.com/YoYoGames/YoYoStudio/files/14920878/ui.log)

### Steps To Reproduce

1. Start GameMaker
2. Open any project
3. Try to execute any shortcut that uses modifier keys
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

 IDE v2024.400.0.535  Runtime v2024.400.0.554

### Which operating system(s) are you seeing the problem on?

Windows 11, Windows 10

### Are you running GameMaker from inside your Steam library?

No

### ui.log File

- [X] I have attached my ui.log file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by SmithTom6304** [comment]
Fixed the issue with control/shift not triggering. This was occuring when laptop mode was disabled.
Fixed the issue with captions displaying an extra "+" sign on Windows.
Missed the issue with deserializing the hotkeys, but that is not connected. As the next beta has already started building, I'm going to split that into a separate issue so we can verify that the rest of this has been fixed as it's a high priority one.

**Comment by caitlinrmcintyre** [comment]
I'm still having issues using CTRL+C and CTRL+V in the room editor, it works as expected elsewhere

**Comment by SamTHodson** [comment]
It appears shortcuts without modifier keys contain a '+' in their caption, however the previous issue with the extra '+' has been fixed for shortcuts with modifiers

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/85949835/887af702-5574-4711-8dd9-0102a8fa83a8)

**Comment by SmithTom6304** [comment]
> It appears shortcuts without modifier keys contain a '+' in their caption, however the previous issue with the extra '+' has been fixed for shortcuts with modifiers
> 
> ![image](https://private-user-images.githubusercontent.com/85949835/321258985-887af702-5574-4711-8dd9-0102a8fa83a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NjY4NjksIm5iZiI6MTcxMjc2NjU2OSwicGF0aCI6Ii84NTk0OTgzNS8zMjEyNTg5ODUtODg3YWY3MDItNTU3NC00NzExLThkZDktMDEwMmE4ZmE4M2E4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDE2MjkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4ZDA0MDg2YTYzNzQ1MzkwYTdmY2E5M2NlMGRmNTRkODliMDY5MGEzYTlhNzBlYjRhYWNmYmJjMzZjMjhiMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tc3Q-uiquXY245zJAl8mntsHz9_CX_wIaQwWsgPmPzw)

This should now be fixed.

**Comment by Emc1923** [comment]
Verified fixed  IDE v2024.400.0.539  Runtime v2024.400.0.558.
