### ISSUE TITLE
[GPU Texture Compression] Compression failure due to spaces in folder name.

### ISSUE THREAD

**Issue by GameDevTosh** [YoYoGames/GameMaker-Bugs#5720]
### Description

I figured I would report this just in case.

[As mentioned here last week](https://github.com/YoYoGames/GameMaker-Bugs/issues/5495#issuecomment-2079248345) when a projects path has a folder with spaces in its name, the compression fails with this error message:
![325966430-b081b40d-852a-472d-9a60-3508f306d519](https://github.com/YoYoGames/GameMaker-Bugs/assets/85319605/22a03ae4-7ab6-48b9-8c06-fee868c1d9a2)

Moving the directory with **Save As** allows the compression to work, but without a proper error to point out what exactly is the issue, no-one could figure this out normally. It would also require moving projects out of source controlled folders with spaces in its name, and pointing github back to those folders, which isn't great.

### Expected Change

Allowed spaces in folder paths. This should be allowed by default in the extension, rather than trying to edit the files to accomplish it.

### Steps To Reproduce

As long as the folder your project is in has spaces somewhere in the path (in my case its A:\Game Maker Projects\Source Control\GPU_Test) the compression will fail when the project is run. In the pic above it assumes the directory is A:\Game rather than the full folder name

So, steps to reproduce:
- Open the included YYZ. This project has a texture group with BCN -u4 option and the extension. Project here: [GPU Test.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/15193319/GPU.Test.zip)
- Make sure the project is saved to a folder that has spaces in its name
- Run the project, observe the crash due to the name
- **_Save As_** the project to a folder with no spaces
- Run the project, observe it runs correctly

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.0 (Monthly), 2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Which platform(s) are you having trouble building this project for?

Windows

### Are you running GameMaker from inside your Steam library?

Yes

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by JonnoRobson** [comment]
I've updated the scripts in the texture encoding extension (https://github.com/YoYoGames/GM-GPUTextureCompression) so they should now work correctly when there are spaces in the project path.

**Comment by cla8194** [comment]
Just tested this, right now the problem has not been solved. After replacing the spaces in project name and folder it's working as expected

**Comment by GameDevTosh** [comment]
So this issue still remains. I have tried opening my project that has spaces in its name and get this error:
![New Error](https://github.com/YoYoGames/GameMaker-Bugs/assets/85319605/a5746ff6-63b0-4c54-a86f-7e9258ceba4e)

Saving the project to a folder with no spaces will correct this. One other user (seen above) has also confirmed this to be the case in the discord help forums. On saving elsewhere with no spaces it works as intended.
![success if no spaces](https://github.com/YoYoGames/GameMaker-Bugs/assets/85319605/9de3a5c5-b366-40d2-9972-ea7cfd562207)

**Comment by GameDevTosh** [comment]
> Apologies, I've updated the texture encoding extension again. These changes have now fixed the issue for me when testing with a small project that I created with spaces in the name.

Can confirm it works, thank you!

**Comment by GameDevTosh** [comment]
Was just mentioned by Juju that this issue still exists on Mac/Linux. This fix seems to only work on windows.

**Comment by JonnoRobson** [comment]
Issues with spaces in folder names should now also be resolved on Mac/Linux - see the mentioned issue for details on the causes/fixes.

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.6.0.156  Runtime v2024.6.0.205
