### ISSUE TITLE
In-Game: [HTML5] part_particles_burst() results in a page error

### ISSUE THREAD

**Issue by aidinzolghadr** [YoYoGames/GameMaker-Bugs#5791]
### Description

Particles work fine in Windows build but show a black screen on HTML5. 

Here is my code:

Create:
`particle_system = part_system_create_layer("Effects", false);`

Step:
```
var _part = particle_get_type(ScoreParticleSystem);
part_particles_burst(particle_system, obj_score_text.x, obj_score_text.y + 10, _part);
```

Googling tells me it was a problem that fixed 2 years ago.

I "Clean"-ed the project and also "use built-in particle system" is checked in its build settings, as the default is.

Here is the Firefox's Console error:

```
Uncaught ReferenceError: _1y is not defined
    particle_get_info http://127.0.0.1:51264/html5game/four_lanes_game.js?cachebust=1538700042:927
    gml_Script_particle_get_type http://127.0.0.1:51264/html5game/four_lanes_game.js?cachebust=1538700042:67
    gml_Object_obj_bullet_Step_0 http://127.0.0.1:51264/html5game/four_lanes_game.js?cachebust=1538700042:68
    _86 http://127.0.0.1:51264/html5game/four_lanes_game.js?cachebust=1538700042:3790
    _86 http://127.0.0.1:51264/html5game/four_lanes_game.js?cachebust=1538700042:3576
    _86 http://127.0.0.1:51264/html5game/four_lanes_game.js?cachebust=1538700042:3627
    _St3 http://127.0.0.1:51264/html5game/four_lanes_game.js?cachebust=1538700042:4554
    _ot3 http://127.0.0.1:51264/html5game/four_lanes_game.js?cachebust=1538700042:4565
    _Ss3 http://127.0.0.1:51264/html5game/four_lanes_game.js?cachebust=1538700042:4541
[four_lanes_game.js:927:380](http://127.0.0.1:51264/html5game/four_lanes_game.js?cachebust=1538700042)
    particle_get_info http://127.0.0.1:51264/html5game/four_lanes_game.js?cachebust=1538700042:927
    gml_Script_particle_get_type http://127.0.0.1:51264/html5game/four_lanes_game.js?cachebust=1538700042:67
    gml_Object_obj_bullet_Step_0 http://127.0.0.1:51264/html5game/four_lanes_game.js?cachebust=1538700042:68
    _86 http://127.0.0.1:51264/html5game/four_lanes_game.js?cachebust=1538700042:3790
    _86 http://127.0.0.1:51264/html5game/four_lanes_game.js?cachebust=1538700042:3576
    _86 http://127.0.0.1:51264/html5game/four_lanes_game.js?cachebust=1538700042:3627
    _St3 http://127.0.0.1:51264/html5game/four_lanes_game.js?cachebust=1538700042:4554
    _ot3 http://127.0.0.1:51264/html5game/four_lanes_game.js?cachebust=1538700042:4565
    _Ss3 http://127.0.0.1:51264/html5game/four_lanes_game.js?cachebust=1538700042:4541
```

### Expected Change

The function works correctly on HTML5

### Steps To Reproduce

1. Start GameMaker
2. Open the attached project: [html5_particle_bug.zip](https://github.com/user-attachments/files/15954367/html5_particle_bug.zip)
3. Compile and run HTML5 version
4. Shoot one of enemies with Space key, which results in displaying the particle
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.0 (Monthly)

### Which platform(s) are you seeing the problem on?

HTML5

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by jackerley** [comment]
Thanks for reporting this issue, but in order to investigate we will need a small project which shows this issue. Please report this issue again, but ensure you have a suitable project open at the time and you have checked the “Include Project” option on the bug form. Please don't submit an .exe for the project, please submit a .yyz of your project

**Comment by aidinzolghadr** [comment]
Hi,

thanks for the reply. I did upload the project report created by game maker and linked it above as I could not find how to upload directly to GitHub, if that is what intended.

Cheers.

**Comment by jackerley** [comment]
When reporting your bug from the IDE please tick the Privately attach project which will upload your project with your bug report in such a way that only our staff can download it. megaup that you have used to upload the zip to requires it downloading as an .exe which I can't do for IT security reasons.

**Comment by aidinzolghadr** [comment]
1) There is no tick, it asks if you want to include the project and I said yes.
2) The file I uploaded does not have an .exe but has .yyz and is what GameMaker generated via Help->Create Your Contact Us Package.

**Comment by jackerley** [comment]
When I go to download the zip file from megaup.net I can only download it as an .exe which I am not prepared to do. You have not uploaded your project when you submitted the bug, otherwise it would be attached to the issue and not be using megaup.net. You will need to resubmit from the IDE or upload your project to somewhere that doesn't re-package your upload.

**Comment by aidinzolghadr** [comment]
I think you probably clicked on an ad or something. I uploaded to a couple more places so at least hopefully one of them would work. If not please tell me where do you want me to upload it:

https://www.dropbox.com/scl/fi/fle4veuih2iwnfkkgvfhi/html5_particle_bug.zip?rlkey=10wduqkvohcsxn6b56c2oy2fv&dl=0

https://filebin.net/7o6omuro49wcj9qj/html5_particle_bug.zip

https://www.filemail.com/d/kadsrqaccrztabm

https://fastupload.io/2ea824bcd0c8a6fd

**Comment by jackerley** [comment]
Thanks I have your project and a fix now.

**Comment by aidinzolghadr** [comment]
Great job! Let me know if you wanted me to test or something.

**Comment by Emc1923** [comment]
Verified fixed, closing.

**Comment by aidinzolghadr** [comment]
Great, which release will have it?

**Comment by jackerley** [comment]
It is fixed in the current June Beta

**Comment by aidinzolghadr** [comment]
I still have the same issue. I got the latest beta version, unchecked Obfuscation in HTML5, got the HMTL5 runtime and assigned it and when it wants to run the particle browser's console says:

`Unhandled Exception - TypeError: particleType is undefined in file http://127.0.0.1:51264/scripts/functions/Function_Particles.js at line 172`

and here is the browser's debugger: [https://pastebin.com/cWXwJftL](https://pastebin.com/cWXwJftL)

BTW I'm using Firefox.

**Comment by YYDan** [comment]
Yeah, same error for me also, so reopening.

Beta IDE v2024.600.0.579 Beta Runtime v2024.600.0.605

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.580  Runtime v2024.600.0.607
