### ISSUE TITLE
[YYC] Off by 1 `int64`

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Bugs#5940]
### Description

There is an issue with an off by one value in the YYC builds of games.

### Expected Change

1152921504606846975 - 1 should equate to 1152921504606846974

### Steps To Reproduce

```gml
var _test = 0xFFFFFFFFFFFFFFF //1152921504606846975
show_debug_message(["_test 1", _test])
_test -= 1
show_debug_message(["_test 2", _test])
_test += 1
show_debug_message(["_test 3", _test])

show_debug_message([typeof(_test), int64(_test), _test, 0xFFFFFFFFFFFFFFF])
```
Yet the YYC output says:
```
[ "_test 1",1152921504606846975 ]
[ "_test 2",1152921504606846976 ]
[ "_test 3",1152921504606846976 ]
[ "number",1152921504606846976,1152921504606846976,1152921504606846975 ]
```
however on VM builds it's correct:
```
[ "_test 1",1152921504606846975 ]
[ "_test 2",1152921504606846974 ]
[ "_test 3",1152921504606846975 ]
[ "int64",1152921504606846975,1152921504606846975,1152921504606846975 ]
```

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2024.6 - integer constants are now handled as integers rather than being turned into REAL values

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.568  Runtime v2024.600.0.595

**Comment by tinkerer-red** [comment]
IDE v2024.1300.0.785 Beta Runtime v2024.1300.0.790

Bug still exists for YYC:

![Image](https://github.com/user-attachments/assets/55a61724-2bd8-4490-b4e0-af65b6aae3e9)
