### ISSUE TITLE
Code Editor 2: Changing theme colors doesn't apply until changing to a different theme and back again

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6267]
### Description
If you change colors in the theme settings, the colors won't actually change in the editor. To make it register, you need to swap to a different theme, apply it, and then change back.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/b9324603-5ee3-4c8f-96de-545627ea56d5

Changing the background color in particular has some strange results:

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/1eb3fc10-ee05-4496-92a1-f738583abad5

### Steps To Reproduce
Change a color in the theme settings window.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.575 Runtime v2024.600.0.601

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[1b1ee8f1-08bc-4b6b-8261-45961e112b47](https://api.gamemaker.io/api/github/downloads/1b1ee8f1-08bc-4b6b-8261-45961e112b47)

**Comment by zreedy** [comment]
Fixed

**Comment by caitlinrmcintyre** [comment]
Verified fix for the first part, but background is still broken for me in IDE v2024.800.0.588  Runtime v2024.800.0.612 so reopening.

https://github.com/YoYoGames/GameMaker-Bugs/assets/131007845/349f8607-d98c-4945-a353-89e1c03e72fc

**Comment by alicemoretti** [comment]
All fixed on  IDE v2024.1300.0.715  Runtime v2024.1300.0.728. 

Thank you.
