### ISSUE TITLE
Code Editor 2: Typing out a full function name without using autocomplete after "variable =" will make the argument helper tooltip not appear

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6276]
### Description
If you type `variable = place_m` and then use autocomplete to finish, the helper tooltip for arguments will appear. But if you type out the full function name yourself, like `variable = place_meeting(`, the tooltip will not appear.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/f1d36553-0dcd-47d5-ae73-efb91066d525

### Steps To Reproduce
Type `variable = place_meeting(` or any other function name and don't use autocomplete.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.576 Runtime v2024.600.0.602

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[06d8ec77-6918-4662-8759-e0aa831f83a2](https://api.gamemaker.io/api/github/downloads/06d8ec77-6918-4662-8759-e0aa831f83a2)

**Comment by zreedy** [comment]
Fixed. The dynamic filter heuristic was not filtering when non candidate specifically matched resulting in excessive symbols to be retrieved and then truncated. Depending on if the symbol that should've been returned for code completion was truncated or not (top 80 items) you may or may not see the above behavior.

**Comment by Emc1923** [comment]
If you select the suggested function from the autocomplete tooltip instead of using the enter key the issue persists.
![argCE2](https://github.com/user-attachments/assets/4499d5a5-116a-40cf-9f32-51f1ac6a15bf)

**Comment by zreedy** [comment]
The gif shows the parameter tooltip being shown. The code completion list doesn't immediately prompt, I'm not sure that's really a bug though. If you begin typing it will prompt.

**Comment by Emc1923** [comment]
Verified fixed in Beta IDE v2024.1100.0.626  Runtime v2024.1100.0.652 as per latest comments above.

**Comment by zreedy** [comment]
Upon discussion, it was determined that this inconsistency should be addressed. Clicking on a Code Completion Item in the Code Completion List will now prompt a new Code Completion Window after filling the selected entry if that entry was a function call.
