### ISSUE TITLE
Code Editor 2: Pressing a key that doesn't type anything can make autocomplete show "no suggestions" when typing function arguments

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6285]
### Description
When autocomplete appears for no characters typed, such as when you first start a function argument, hitting a key that doesn't actually type anything will clear it to "no suggestions". I found this while trying to take a screenshot of it, and discovered pressing print screen made autocomplete go blank. It also happens for other keys that doesn't type, such as F1-F12, caps lock, insert, print screen, and most importantly shift. It does NOT disappear when pressing ctrl or alt.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/039d4ccb-222d-4d4d-8f0d-297b9fa54313

### Steps To Reproduce
Type out any function, and when autocomplete shows up for the arguments, press a key that doesn't type a character.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.576 Runtime v2024.600.0.602

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[9eb39b51-f23f-4125-9172-6fb2cf579656](https://api.gamemaker.io/api/github/downloads/9eb39b51-f23f-4125-9172-6fb2cf579656)

**Comment by zreedy** [comment]
Fixed

**Comment by caitlinrmcintyre** [comment]
Reopening as I'm still seeing the issue in IDE v2024.800.0.588  Runtime v2024.800.0.612.

**Comment by zreedy** [comment]
This is fixed. Verified that the completion list dismisses when a non-printing character is pressed.
