### ISSUE TITLE
Code Editor 2: Opening creation code for multiple instances doesn't show any of the instances after the first one until reload

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6290]
### Description
If you open up creation code to edit, it'll pop up for the first instance just fine. But if you open more of them, they won't show up in the creation code window until you either close the tab and reopen it, or reload the project.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/8cba9894-8dbf-4aff-ab14-04a6b92d35e4

### Steps To Reproduce
Place multiple instances in a room, and try to open creation code for a bunch of them.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.576 Runtime v2024.600.0.602

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[5634b137-fc60-4892-a61e-93aef5a5ae95](https://api.gamemaker.io/api/github/downloads/5634b137-fc60-4892-a61e-93aef5a5ae95)

**Comment by zreedy** [comment]
Fixed

**Comment by zreedy** [comment]
Prematurely closed, reopening. The issue is fixed pending merge.

**Comment by mgeddesGM** [comment]
issue still present  IDE v2024.800.0.595  Runtime v2024.800.0.619

**Comment by zreedy** [comment]
Unable to reproduce with desk testing. Closing again, if this is still reproducible please provide a project and video demonstrating the issue.

**Comment by Emc1923** [comment]
Looks fixed from the room editor in  IDE v2024.800.0.603  Runtime v2024.800.0.625, so closing this one. For the inspector button see issue linked above.
