### ISSUE TITLE
In-Game: dbg_drop_down() should add support for scrolling the list using mouse wheel

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#6416]
### Is your feature request related to a problem?

You can't scroll up and down in a debug drop down(/combo box/whatever) with the mouse wheel, only by clicking on the drag handle thingy. This gets difficult if you have a list with a lot of items in it.

### Describe the solution you'd like

Allow the drop down to scroll with the mouse wheel

Bonus points if we could be allowed to expand the window:

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/7087495/d5d618ac-d014-458a-b73b-e3563e443c49)

### Additional context

See also #2975 for some other ways debug views could be improved

**Comment by rwkay** [comment]
Fixed in 2024.8 - imgui mouse wheel now supported on Windows, Mac and Linux

**Comment by gnysek** [comment]
Does it solve https://github.com/YoYoGames/GameMaker-Bugs/issues/2855 too, or that would require separate touch event support?

**Comment by cameron-home** [comment]
Verified working in IDE v2024.800.0.599  Runtime v2024.800.0.622 on Windows, but issue still occurs in same version on macOS so reopening.

**Comment by rwkay** [comment]
Fixed the macos issue in 2024.8

**Comment by YYBartT** [comment]
Added a line to the `dbg_drop_down()` manual page mentioning that you can use the mouse wheel to scroll through a longer list of values.

**Comment by cameron-home** [comment]
Verified that scrolling now works on both Windows and macOS in IDE v2024.800.0.606  Runtime v2024.800.0.630.
