### ISSUE TITLE
Code Editor 2: When adding moments or events to a sequence, automatically creating a new function will create a broken function

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6478]
### Description
There are two different issues with these automatically added moments. First, they won't actually be recognized by the sequence properly, and will show up in red + will not autocomplete. Additionally, repeating the action and adding another moment will just create the same function again, instead of creating a new function.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/d0a8fcc4-001f-4067-812e-910236cb8537

### Steps To Reproduce
With CE2 enabled, create a sequence and add a moment to it. Hit the + button to create a new function for it. Add more moments and repeat.

Note: The same will happen when creating sequence events by creating new event definitions.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.585 Runtime v2024.600.0.609

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[a9983540-2ed7-4dab-acdf-2c499d37ddd2](https://api.gamemaker.io/api/github/downloads/a9983540-2ed7-4dab-acdf-2c499d37ddd2)

**Comment by zreedy** [comment]
Duplicate. Same root issue as https://github.com/YoYoGames/GameMaker-Bugs/issues/6479

**Comment by Emc1923** [comment]
https://github.com/YoYoGames/GameMaker-Bugs/issues/7011 has had no effect on reproducing this issue -  disabling/reenabling code editor 2 is not required to reproduce.

**Comment by zreedy** [comment]
Fixed

**Comment by Emc1923** [comment]
The issue still happens as described with moments and events as of  IDE v2024.1000.0.621  Runtime v2024.1000.0.647

**Comment by zreedy** [comment]
Fixed and merged

**Comment by mgeddesGM** [comment]
this is now crashing the IDE on first attempt using  IDE v2024.1100.0.666  Runtime v2024.1100.0.692

1. open a project
2. press the "add moment", the moment modal shows
3. then i press the "add function" button then the ide crashes
4. reopen the project and repeat and it works as expected
5. open or create a new project and the above will happen again

[ui.log](https://github.com/user-attachments/files/17598608/ui.log)

**Comment by mgeddesGM** [comment]
@zreedy is this going to be in Nov?

**Comment by mgeddesGM** [comment]
the above is still happening in IDE v2024.1100.0.677  Runtime v2024.1100.0.701

**Comment by mgeddesGM** [comment]
happened on second and third time in
[ui.log](https://github.com/user-attachments/files/17751962/ui.log)
