### ISSUE TITLE
Code editor 2: Autocomplete stops showing proper completion for arguments when calling one function as an argument for another

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6487]
### Description
If you run a function directly as an argument for another function, the inside function will not have proper autocomplete.
Type something like 
```
instance_nearest()
``` 
and autocomplete will fill out proper things for the x, y, and object arguments. 
But if you do this instead
```
show_debug_message(instance_nearest())
``` 
None of the instance_nearest arguments will have autocomplete for anything except the things that always show up in autocomplete regardless of context.

Here's an example using object_exists inside of show_debug_message. Object1 does not get suggested, even though it did when object_exists was called on it's own.

https://github.com/YoYoGames/GameMaker-Bugs/assets/100942509/4068ecdd-5fcb-416b-9d01-dec9db9d0027

### Steps To Reproduce
Type any function that has arguments as an argument for another function, and then look at autocomplete

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.585 Runtime v2024.600.0.609

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[44a3f81a-f1f0-4e0b-b086-64ff6dfd7d20](https://api.gamemaker.io/api/github/downloads/44a3f81a-f1f0-4e0b-b086-64ff6dfd7d20)

**Comment by zreedy** [comment]
Fixed.

**Comment by mgeddesGM** [comment]
still present as of  IDE v2024.800.0.591  Runtime v2024.800.0.615

**Comment by zreedy** [comment]
Fixed again, regression in the assignment of the dynamic filtering heuristic. The heuristic was assigned to the first argument despite diving into nested function calls.

**Comment by caitlinrmcintyre** [comment]
Verified fix in  IDE v2024.1100.0.623  Runtime v2024.1100.0.649, thanks.
