### ISSUE TITLE
Code Editor 2: Double-click-and-drag can give incorrect selections when dragging across multiple lines

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#6760]
### Description
If you double-click drag, it's supposed to snap the selection to whole words. However, if you drag to lines of code that are longer than the original one you selected, the words on longer line will only get partially selected. The selection will also go haywire if you drag to the very start of the original word you selected.

https://github.com/user-attachments/assets/6146e8d0-45f6-427f-b8e1-de50e9a7765b

### Steps To Reproduce
Double-click drag across some code with varying line/word lengths.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.593 Runtime v2024.800.0.617

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[0c861fbb-93df-4aa1-bb59-d2a1455e12af](https://api.gamemaker.io/api/github/downloads/0c861fbb-93df-4aa1-bb59-d2a1455e12af)

**Comment by zreedy** [comment]
Fixed

**Comment by caitlinrmcintyre** [comment]
Verified fix for the partial selection on larger words, but I'm still seeing an issue when dragging to the start of the original word you select in Beta IDE v2024.1100.0.623  Runtime v2024.1100.0.649.

https://github.com/user-attachments/assets/bc2a30e4-aa11-4280-a511-b268fad1d300

**Comment by zreedy** [comment]
This additional issue is related to https://github.com/YoYoGames/GameMaker-Bugs/issues/6770
Fixed

**Comment by sihammill** [comment]
Fix verified in IDE v2024.1100.0.653  Runtime v2024.1100.0.679
