### ISSUE TITLE
Code Editor 2: Double click+drag should retain initially selected word when dragging left

### ISSUE THREAD

**Issue by backYard321** [YoYoGames/GameMaker-Bugs#6770]
### Is your feature request related to a problem?

In other programs with selectable text, double click+drag works like this:
![web browser click and drag](https://github.com/user-attachments/assets/eaf4f75e-aff6-42cc-b3e4-110a163e9a3c)

However, in CE2, it works like this:

![CE2 click and drag](https://github.com/user-attachments/assets/8179592d-3ccd-49a9-8604-3d57fcf96cdc)

The word that is initially selected is no longer selected once you drag to the left of it. The current behaviour is detrimental to my workflow, and also contrary to how this feature works in any other program I've used. Text editors, web browsers, discord, etc all use the above behaviour.

### Describe the solution you'd like

Keep the initially selected word in the selection when you double-click and drag left.

**Comment by thennothinghappened** [comment]
I think I've noticed this and been annoyed by it but not quite enough to remember to report it lol. Thank you for doing that!

**Comment by zreedy** [comment]
Fixed

**Comment by backYard321** [comment]
related to #8799 - this is not fixed when the selected word is 1 character long (eg: `x`, `2`, `+`, `(`, etc)
