### ISSUE TITLE
Preferences: Clicking "restore defaults" in Code Editor 2 shows a disable CE2 confirmation message even if CE2 is already disabled

### ISSUE THREAD

**Issue by caitlinrmcintyre** [YoYoGames/GameMaker-Bugs#7009]
### Description

When verifying [#6600](https://github.com/YoYoGames/GameMaker-Bugs/issues/6600), I noticed firstly that clicking "restore defaults" in CE2 shows a confirmation message about disabling CE2. This message appears even if CE2 is already disabled.

![image](https://github.com/user-attachments/assets/02408b99-03ea-4f98-b9c6-0084f0e2aea0)

When clicking cancel and going into CE2 theme and clicking "restore defaults" there, I received the same message (this message didn't appear when closing and reopening preferences and ONLY clicking "restore defaults" in CE2 theme). 

![image](https://github.com/user-attachments/assets/40e8ef3e-83e7-45b0-a3cf-c51d2a71522a)

 Beta IDE v2024.800.0.599  Runtime v2024.800.0.622

### Steps To Reproduce

1. Start GameMaker and go to Preferences > CE2.
2. Ensure CE2 is disabled and click "restore defaults".
3. See the message about disabling CE2.
4. Click cancel and go to Theme and click "restore defaults" again and see the same message.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by YYDan** [comment]
Appears to have been caused by the change in https://github.com/YoYoGames/GameMaker-Bugs/issues/7011

**Comment by stuckie** [comment]
This should now be fixed as part of https://github.com/YoYoGames/YoYoStudio/pull/10883

**Comment by sihammill** [comment]
The issue is still present in Beta IDE v2024.1100.0.685  Runtime v2024.1100.0.707

https://github.com/user-attachments/assets/007aa1a0-bcb8-44a8-a161-a26ca051e750
