### ISSUE TITLE
In-Game: [YYC] collision_rectangle() causes silent crash in early 2024.800 runtimes

### ISSUE THREAD

**Issue by tabularelf** [YoYoGames/GameMaker-Bugs#7075]
### Description
While testing one of my games, I noticed that collision_rectangle_list was causing a silent crash. Replicated the issue with what I believe might be the case. 

### Steps To Reproduce
1. Run project on YYC
2. See crash in output

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.602 Runtime v2024.800.0.624

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
Windows

[32557554-d163-488b-885d-b4e4c8ce0427](https://api.gamemaker.io/api/github/downloads/32557554-d163-488b-885d-b4e4c8ce0427)

**Comment by jackerley** [comment]
Fixed, same issue as #6767

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2024.800.0.605  Runtime v2024.800.0.628. 

Thank you.

**Comment by danieltjewett** [comment]
I am still getting silent crashes in both YYC and VM with `collision_rectangle_list` on runtime `v2024.8.1.218` and `v2024.11.0.226`:

![Image](https://github.com/user-attachments/assets/8d99618b-7eea-4b53-8107-c35b82b086e7)

```GML
var num = selectMultiple || !hasNextTargetAvailable ?
		collision_rectangle_list(global.camera.view_left, global.camera.view_top, global.camera.view_left + global.camera.view_width, global.camera.view_top + global.camera.view_height, obj_Interactable, false, true, _tempList1, true)
		: 0;
```

**Comment by KormexGit** [comment]
@danieltjewett Would probably be good to make a new report, comments on closed reports don't usually get seen in my experience

**Comment by danieltjewett** [comment]
@KormexGit Are you experiencing this issue by chance?  I'll most likely make an issue later tonight or tomorrow.  We're working out the kinks of upgrading to `2024.11` after being on `2024.2` for several months.

**Comment by KormexGit** [comment]
@danieltjewett A simple test of just calling collision_rectangle_list does not crash for me, so if I were to guess there's some additional condition required that your project has happening

**Comment by danieltjewett** [comment]
@KormexGit Agreed.  We're using `collision_rectangle_list` all over the place.  That is why I haven't created an issue yet.  That specific usage is on a clean up / game restart event, so maybe it has something to do with that?  I still need to investigate.

I have found that it is easier for the team to have easily reproducible bugs than what I posted above.  My posting above is for searching in Github, if someone else ever were to encounter the issue.  I will link the new issue (once I find more) here as well.

**Comment by danieltjewett** [comment]
Upon further investigation, this code of ours shouldn't even be running, because we have a flag set that _should_ gate this on game end.  However, this gate is [obviously] not working correctly.  My assumption is that `global.camera` or `_tempList1` has been destroyed, and thus why the error is being thrown.  I'd like to see this throw an error, and not a silent crash.  However, the complexity of this is not worth trying to figure out, and may not even be related to the issue posed in the title.
