### ISSUE TITLE
In-Game: [YYC] Creating a large array literal via code can cause a silent crash

### ISSUE THREAD

**Issue by GameDevTosh** [YoYoGames/GameMaker-Bugs#7082]
### Description
This one was a pain to find, but after deleting 80% of my project I was able to narrow it down.

If you make a large enough array literal of structs with multi-dimensional arrays full of constructor calls (in this case, 3500 lines of code), Gamemaker will silently crash in YYC only with "exited with non-zero status (-1073741571)". This seems to happen in all versions of GM, including latest Beta, the version this report is being made in.
![error](https://github.com/user-attachments/assets/cad67af5-86e9-49b4-8335-dffd743c57c9)

The included project has a full reproduction.

P.S: This project runs in VM, GMRT VM, and GMRT Native. Its is **ONLY** in YYC that this issue happens.

### Steps To Reproduce
- Run the project in YYC
- Observe the crash near the end of the build
- Run the project in VM, GMRT VM, or GMRT Native
- Project will run just fine

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.602 Runtime v2024.800.0.624

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
Windows

[fae7009d-8006-4ccb-bdd4-9ed8aa5dc541](https://api.gamemaker.io/api/github/downloads/fae7009d-8006-4ccb-bdd4-9ed8aa5dc541)

**Comment by backYard321** [comment]
I get a similar silent crash testing YYC - I don't use multi-dimensional arrays, but I do store a lot of structs containing methods in arrays.

**Comment by GameDevTosh** [comment]
So saving the array (made in a script asset, not inside a function) to json/file in VM and then loading that file instead of via script asset makes it work in YYC. So its really something to do with making large array literals, or making large array literals in script assets.

**Comment by rwkay** [comment]
I have implemented an improvement in 2024.11 that allows the enclosed project to compile - it is not an overall fix for giant data sets being implemented as code - I would still advocate using data files for large amounts of data.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.646  Runtime v2024.1100.0.666

**Comment by GameDevTosh** [comment]
On todays beta version, this issue still happens with the same project that was submitted with this report. VM works fine as usual.![Image](https://github.com/user-attachments/assets/2a49ac05-9440-4371-9994-0994572dfb53)

**Comment by rwkay** [comment]
Check this is working...

**Comment by GameDevTosh** [comment]
Verified it again that it does not work in .680. However, using a squirrel build of .666, it does work as QA had said. It is only in latest beta (.680 runtime) that it does not.![Image](https://github.com/user-attachments/assets/da822076-9646-4b5c-b9b2-d5a1d1493004)

**Comment by rwkay** [comment]
Fixed in 2024.11 again.... So it turns out the earlier fix was in their but a fix for a knock on issue caused the original problem to reappear - it turns out that creating giant arrays in GML like this is not a good idea... but... I was able to address the issue in a different way and I have now made YYC generate array literals in a slightly different way that does not create quite so many return variables (causing the runtime to run out of stack space).  So this should be back working now.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.659  Runtime v2024.1100.0.685

**Comment by rwkay** [comment]
I have had to reopen this issue as it caused knock ons for other project and the "fix" did not work in the general case - I am going to have to put this on the backlog for now as the real fix for this is GMRT (I have added the gmrt label on this so it is checked) - if you are looking to fix this in your code for the current runtime then you need to look at breaking up your giant declaration into different functions that create the different data you require - perhaps one per sub-structure (looks like it is data for scenes or rooms) - just putting them into anonymous functions would work.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2026.100.0.1119  Runtime v2026.100.0.1080 gmrt 0.22.31
