### ISSUE TITLE
[YYC] Compilation failure in YYC with default argument that is an entry in an array 

### ISSUE THREAD

**Issue by jackerley** [YoYoGames/GameMaker-Bugs#7171]
### Description

Attempting to compile the following 
function gui_posx(__x, __camera = view_camera[0]){
	return (__x - camera_get_view_x(__camera)) * (display_get_gui_width() / camera_get_view_width(__camera));
}
in YYC gives a compile error Error : gml_GlobalScript_lib_functions(97) : Assignment of an empty value (function does not return anything?)

in the linked project https://drive.google.com/file/d/1C6Wr_nqfDuDp2-Dofq1izyyiS7budhwR/view?usp=drive_link

### Steps To Reproduce

1. Start GameMaker
2. Attempt to build for YYC 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which platform(s) are you seeing the problem on?

Windows, PlayStation 5

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2024.8

**Comment by alicemoretti** [comment]
Verified that a note has been added to the page for Script Functions and Variable in the newest version of the Manual. Thank you.

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2024.800.0.614  Runtime v2024.800.0.637

**Comment by cameron-home** [comment]
Getting the following compile error in LTS IDE v2022.0.3.67  Runtime v2022.0.3.80:
![Image](https://github.com/user-attachments/assets/24881840-9ed3-4c83-b53b-4944256a087f)

@rwkay

**Comment by alicemoretti** [comment]
Still getting the same error Cameron posted on LTS IDE v2022.0.3.74  Runtime v2022.0.3.85. 

Failing this for LTS.

**Comment by jackerley** [comment]
The linked project won't work in LTS as it uses is_instanceof() which hasn't been added to LTS. The enclosed project should be sufficient to show the fix. [comptest.zip](https://github.com/user-attachments/files/17432960/comptest.zip)

**Comment by alicemoretti** [comment]
Awesome! Thank you. 

The new project works on LTS  IDE v2022.0.3.74  Runtime v2022.0.3.85. Setting as verified on LTS.
