### ISSUE TITLE
In-Game: Incrementing a constructor's static variable directly via operators gives an error

### ISSUE THREAD

**Issue by GameDevTosh** [YoYoGames/GameMaker-Bugs#7173]
### Description

Given the following constructor:

```
function Hello() constructor
{
    static variable = 0;
    
    static add = function() {
		variable++;
    }
}
Hello();
```

Calling either of these two lines of code to increment the static will give an unexpected code error in-game:

Hello.variable++;
Hello.variable += 1;

Error message:
```
############################################################################################
ERROR in action number 1
of Create Event for object Object1:
Unable to find any instance for object index '100002' name '<undefined>'
 at gml_Script_add@anon@82@Hello@Script1 (line 6) -         Hello.variable++;
############################################################################################
gml_Script_add@anon@82@Hello@Script1 (line 6)
gml_Object_Object1_Create_0 (line 3) -        Hello.add();

```

If you however, use this code instead "Hello.variable = Hello.variable + 1;" it will work. 

This happens in 2024.6 and also in newest 2024.8 Beta 4.

### Steps To Reproduce
- Run the project, and try to add to the static using the static struct and using ++ or +=
- Observe the error message
- Change it to instead use variable = variable + 1;
- It will run just fine

### Which version of GameMaker are you reporting this issue for?

2024.6 (Monthly)
IDE v2024.800.0.605 Runtime v2024.800.0.628

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

### Which platform(s) are you seeing the problem on?
Windows

[5c6ea4e9-559d-4c08-a9b1-4657f0d46461](https://api.gamemaker.io/api/github/downloads/5c6ea4e9-559d-4c08-a9b1-4657f0d46461)

**Comment by rwkay** [comment]
Fixed in 2024.8

**Comment by gnysek** [comment]
`Hello.variable += 1;` is still NOT working.

`Hello.variable++;`, `Hello.variable = Hello.variable + 1;` works.

**Comment by GameDevTosh** [comment]
Opened a new report linked above as more operators were tested by gynsek and also seem to be broken. It's only ++ and -- that seem to be fixed in Beta 5.

**Comment by YYDan** [comment]
_From the dupe report:_

Statics are still broken in 2024.8 Beta 5. As previously seen in this previously closed report https://github.com/YoYoGames/GameMaker-Bugs/issues/7173 it seems only the ++ and -- operators were fixed. I opened a new report because more operators were found to be broken, which include the *= and /= operators.

Given this constructor:

```
function Hello() constructor
{
    static variable = 0;
    
    static add = function() {
        Hello.variable++;
    }
}
Hello();

//Hello.variable++; //works
//Hello.variable--; //works
//Hello.variable = Hello.variable + 1; //works
//Hello.variable = Hello.variable - 1; //works
//Hello.variable = Hello.variable * 2; //works
//Hello.variable = Hello.variable / 2; //works, even with 0
//Hello.variable -= 1; //broken
Hello.variable += 1; //broken
//Hello.variable *= 2; //broken
//Hello.variable /= 2; //broken

show_debug_message(Hello.variable);
```

The ones that show as broken are still broken.


[e802cbe0-cc1d-4a5e-8f72-3e7daf49c961](https://api.gamemaker.io/api/github/downloads/e802cbe0-cc1d-4a5e-8f72-3e7daf49c961)

**Comment by rwkay** [comment]
Fixed in 2024.8

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2024.800.0.611  Runtime v2024.800.0.635
