### ISSUE TITLE
In-Game: [HTML5] audio_create_stream will crash if the initial request for the stream file fails

### ISSUE THREAD

**Issue by toby-yoyo** [YoYoGames/GameMaker-Bugs#7804]
### Description
If the initial request for the given stream file fails for some reason, `audio_create_stream` will crash the runtime with the error:
```
Uncaught ReferenceError: srcUrl is not defined
```

### Steps To Reproduce
- Open and run the attached project on HTML5
- Interact with the screen to start the test. The runner should crash at this point.
- Inspect the console and see the error from the description.

### Which version of GameMaker are you reporting this issue for?
IDE v9.9.1.798 Runtime v9.9.1.960

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
HTML5

[956c8f07-1372-4fe4-8a30-4ab6631a8a29](https://api.gamemaker.io/api/github/downloads/956c8f07-1372-4fe4-8a30-4ab6631a8a29)

**Comment by toby-yoyo** [comment]
Fixed an undefined reference to the url used for the stream's request.

**Comment by scott-dunbar** [comment]
HTML5 runner will still crash when calling this function in  IDE v2024.1100.0.630  Runtime v2024.1100.0.655

It is no longer giving the same error however.

**Comment by toby-yoyo** [comment]
Fixed an issue caused by the original fix where the wrong asset index was being used to obtain the URL for the streamed file.

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2024.1100.0.631  Runtime v2024.1100.0.656
