### ISSUE TITLE
In-Game: [HTML5] flexpanel_node_get_data() returns undefined if there is no "data" key, requires adding this manually

### ISSUE THREAD

**Issue by legocris** [YoYoGames/GameMaker-Bugs#7845]
### Description

There are two bugs listed here.
1.- flexpanel_node_get_data returns undefined on html5 target if node has no "data" section on node, while it returns empty struct on other targets. To bypass it is just needed to add an empty struct on data field.
![imagen](https://github.com/user-attachments/assets/dcf91919-68bd-43b7-8b89-21e6fcd5f0b9)

2.- For some reasons the flex panels look different on html5 target than ubuntu desktop. They appear right aligned while on desktop appear centered (desired).
![imagen](https://github.com/user-attachments/assets/8f3f8f3f-6f10-4a86-85a2-f6aa35d8a65a)

Note that the sample package is a modification of the Gurpreet S. Matharoo on flexnode article's example.

### Expected Change

html5 flex_node_get_data returns the same empty struct than desktop does

### Steps To Reproduce

First bug
1. Open the example
2. see that there are not issues with desktop target
3. Play on HTMl5, notice a blank screen with error caused by line 13 of `flexpanels` script (`flexpanel_generate_instance_tree` function).
4. solve it by adding `"data" : {},` on line 25 of obMenuInicio create event

Second bug
1. Play on desktop target. See that all the flex panels are nicely centered
2. (Don't xd) Play on HTML5 because flexes look different, aligned to right or smaller.

Sample Project
[flexpanel_runtime_mod.zip](https://github.com/user-attachments/files/17198807/flexpanel_runtime_mod.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which platform(s) are you seeing the problem on?

Ubuntu

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [x] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2024.11

**Comment by Emc1923** [comment]
Issue persists as of  IDE v2024.1100.0.642  Runtime v2024.1100.0.664. Note, attached sample will error due to the fix implemented for https://github.com/YoYoGames/GameMaker-Bugs/issues/7685
Sample used:
https://api.gamemaker.io/api/github/downloads/11e45c42-aa16-4857-917c-97afe22af42f

**Comment by rwkay** [comment]
> Issue persists as of IDE v2024.1100.0.642 Runtime v2024.1100.0.664. Note, attached sample will error due to the fix implemented for #7685 Sample used: https://api.gamemaker.io/api/github/downloads/11e45c42-aa16-4857-917c-97afe22af42f

But that is a different bug... and just do with the project... it is just the "20%" in the json - the rowGap does not take a percentage.

**Comment by Emc1923** [comment]
The sample I linked is not the user sample, but still reproduces the issue raised here (I think!)

**Comment by Emc1923** [comment]
Edit: The issue I found with the sample I used is a different issue - Verifying this now as of  IDE v2024.1100.0.643  Runtime v2024.1100.0.664 and will create another issue, apologies.

Closing.

**Comment by Emc1923** [comment]
https://github.com/YoYoGames/GameMaker/issues/4434
