### ISSUE TITLE
Code Editor 2: Still possible to delete a parent's event from the child when right clicking the event header

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#8130]
### Description
This is #6231, but triggered in a different way. While you can no longer delete an inherited event from the child using the inspector or the navigation bar, you can still do it by right clicking the event header.

https://github.com/user-attachments/assets/6ccf114d-4e80-4416-a460-8e08beb6e967

### Steps To Reproduce
1. Add an event on an object.
2. Make another object it's child
3. On the child, right click the event inherited from the parent, and select "delete event".
4. The event will be gone from the parent.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.654 Runtime v2024.1100.0.680

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[9610f5d5-ba87-4ee4-a1de-6f219bf2b1b9](https://api.gamemaker.io/api/github/downloads/9610f5d5-ba87-4ee4-a1de-6f219bf2b1b9)

**Comment by KormexGit** [comment]
I just realized this actually applies to ALL of the options in the right click menu. 
Add event adds an event to the parent.
Open parent event does nothing because it acts as if you're already on the parent.
Cut, copy, paste, and duplicate all apply to the parent's event. 
Change event changes the parent's event.
Convert to GML visual converts the parent's event.

https://github.com/user-attachments/assets/8dc7545e-af59-46c2-8f6e-592601d7e093

**Comment by zreedy** [comment]
Fixed.

**Comment by sihammill** [comment]
This issue is still present in the latest green build IDE v2024.13.1.193  Runtime v2024.13.1.242

Deleting the create event from a child object is still removing the create even from the parent object.
