### ISSUE TITLE
Animation curve asset being optimized out as unused despite being used

### ISSUE THREAD

**Issue by KormexGit** [YoYoGames/GameMaker-Bugs#8197]
### Description
One of the animation curves in my project is gone when "Automatically remove unused assets when compiling" is checked, despite it definitely being used. I tried reproducing it in a separate project, but it didn't happen, so here's the whole project. The asset does show up as a ref anim curve when stored in a variable and printed, but trying to actually use it causes errors.

### Steps To Reproduce
1. Open the sample project
2. Open up the script called scr_HELLO_YYG_PLEASE_LOOK_HERE
3. See that the animation curve is definitely used
4. Run the game and see it immediately crash
5. Uncomment line 4 of the script, `show_message("Animation Curve Asset: " + string(animation_curve_wave))`. The game now won't even compile, saying "Unknown type on parameter 0 in optimize call for method string".

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.659 Runtime v2024.1100.0.685

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[39df07ef-aa4e-4efb-a4f5-85684209158f](https://api.gamemaker.io/api/github/downloads/39df07ef-aa4e-4efb-a4f5-85684209158f)

**Comment by rwkay** [comment]
Fixed in 2024.11

**Comment by mgeddesGM** [comment]
@rwkay the  "Unknown type on parameter 0 in optimize call for method string". error is still present in  IDE v2024.1100.0.669  Runtime v2024.1100.0.695.

**Comment by rwkay** [comment]
Fixed in 2024.11

**Comment by rwkay** [comment]
Behaviour of Remove unused has been subtly changed see https://github.com/YoYoGames/GameMaker-Bugs/issues/8312

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.671  Runtime v2024.1100.0.696

**Comment by jackerley** [comment]
GMRT crashes with this project, seems unrelated to reported issue
