### ISSUE TITLE
Updater: The IDE session launched after installing a new update does not allow drag and drop of YYZ files onto the startpage for importing

### ISSUE THREAD

**Issue by scott-dunbar** [YoYoGames/GameMaker-Bugs#8241]
### Description

The IDE session launched after installing a new update does not allow drag and drop of YYZ files onto the startpage for importing

https://api.gamemaker.io/api/github/downloads/88322855-70a9-4b4f-8037-ed420b99f1c9

### Expected Change

Be able to drop files into the IDE after installation

### Steps To Reproduce

1. Start GameMaker
2. Use the In-IDE update to update to the latest version
3. On the start screen of the newly updated version try and drag a YYZ file into the IDE for importing
4. Observe you cannot
5. Restart IDE
6. Observe you now can

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment]
This should be fixed now in 2024.11 as the IDE is now restarted with non-elevated permissions.

**Comment by scott-dunbar** [comment]
This issue is still present as described. Tested updating to  build IDE v2024.1100.0.673  

Because i was unsure if it was the initial version you are updating from or to that triggers the start i tested updating from 

 IDE v2024.1100.0.672 as well as older versions, all had the same outcome.

**Comment by rwkay** [comment]
Not sure what else I can do here... 

I suspect that Steven needs to take a wee look at it.. 

@scott-dunbar when this happens can you please check to see if the IDE has been started with Elevated permissions or not (task Manager, Details tab has an Elevated column that you have to ask to see, should be Yes or No in there - at least Windows 11 has that)

**Comment by scott-dunbar** [comment]
Yes it is running elevated ![Image](https://github.com/user-attachments/assets/4b157bfb-4982-40a5-8f9a-f58fc057b25a)

**Comment by rwkay** [comment]
Fixed in 2024.11 - looks like the code was put into `develop` and not into `2024.11`

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2024.1100.0.680  Runtime v2024.1100.0.702
