### ISSUE TITLE
TestFramework: "string_delete_test #6" in BasicStringTestSuite, string_delete( string local , real const , real const ), 'Hello World!' with the 100th char deleted should be 'Hello World!'

### ISSUE THREAD

**Issue by sihammill** [YoYoGames/GameMaker-Bugs#8382]
### Workflow Artefact URL

https://github.com/YoYoGames/GM-TestFramework/actions/runs/11790645801/artifacts/2174425479

### Test Code

```
addFact("string_delete_test #6", function() {
        
	var vstring = "Hello World!";

	// Check that using an index beyond the size of the string will clamp to the string size
	var res = string_delete(vstring, 100, 1);
	assert_equals(res, "Hello World", 
	"string_delete( string local , real const , real const ), 'Hello World!' with the 100th char deleted should be 'Hello World!'");
  });
```

### Output From The Test

```
Testsuite Name: BasicStringTestSuite
Test Name: string_delete_test #6
stack: gml_Script_anon@43428@BasicStringTestSuite@BasicStringTestSuite:1028
actual: "Hello World!"
description: string_delete( string local , real const , real const ), 'Hello World!' with the 100th char deleted should be 'Hello World!'
expected: "Hello World"
title: Assert values to be equal
```

### Runtime Version

2024.1100.0.703

### Location Of The Test

https://github.com/YoYoGames/GM-TestFramework/blob/01bc8a8d530d3a1db324b12d7ee001c3866ec7a0/projects/xUnit/scripts/BasicStringTestSuite/BasicStringTestSuite.gml#L1021

### Which platform(s) are you seeing the problem on?

Windows

**Comment by DiasFranciscoA** [comment]
This should be fixed already but the Beta build happened too early and didn't catch the fix....
This was a fix to the test that was wrong and so the runner all other tests pass so it should be closable as soon as we have a new Beta that checks the fix

**Comment by sihammill** [comment]
@DiasFranciscoA I can see that this fail is still present in the test run from today, below is the output from the artifact file:

This was for Beta:  IDE v2024.1100.0.683  Runtime v2024.1100.0.705

```
{
      "name": "string_delete_test #6",
      "result": "Failed",
      "time": 5.6e-05,
      "assertions": 1,
      "exceptions": [],
      "errors": [
          {
              "description": "string_delete( string local , real const , real const ), 'Hello World!' with the 100th char deleted should be 'Hello World!'",
              "title": "Assert values to be equal",
              "stack": "gml_Script_anon@43428@BasicStringTestSuite@BasicStringTestSuite:1028",
              "actual": "\"Hello World\"",
              "expected": "\"Hello World!\""
          }
      ]
  }
```

**Comment by sihammill** [comment]
Verified in Beta IDE v2024.1100.0.685  Runtime v2024.1100.0.707
The test now passes as expected with the correct values.
