### ISSUE TITLE
Code Editor 2/LSP: [Ubu IDE] "Language Server for GML" crashes and notifies frequently in 2024.1100 Beta 6

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#8399]
### Description
On Ubuntu, I'm getting some notifiactions about `Language Server for GML has been restarted` and after some time info, that it crashed 3 times, so will be no no longer restarting.

### Steps To Reproduce
1. Open any project
2. Write some code, or just click in few places (including folding/unfolding)
3. Check for blue baloon in top-right corner

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.674 Runtime v2024.1100.0.700

### Which operating system(s) are you seeing the problem on?
Linux Ubuntu 22.04.5 LTS kernel 6.8.0.48

### Attached Files
* Zrzut ekranu z 2024-11-13 20-10-17.png
* ui.log

[74f687e3-96d0-4f78-8b95-ffb91bde601d](https://api.gamemaker.io/api/github/downloads/74f687e3-96d0-4f78-8b95-ffb91bde601d)

**Comment by stuckie** [comment]
We are thinking this is now fixed as of the 2024.1100.0.686 release, if you could confirm that on your setup, thanks!

**Comment by gnysek** [comment]
It still happens on .686:

![Image](https://github.com/user-attachments/assets/73ad6560-f064-4e03-8f9d-f5f4f2cb49a9)

**Comment by zreedy** [comment]
This issue was related to errant `PDEATHSIG` signals raised for the forking thread. The Client spawns the Server via a TPL Task which does not have a guaranteed lifetime of the Client's process. The Server subscribed to the `PDEATHSIG` to be terminated when raised.
Since this signal is raised for thread termination _not_ process termination we cannot rely on it to terminate an orphaned Server process. Instead we now poll the current PPID once a second and gracefully terminate if the PPID migrates.

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.1100.0.713  Runtime v2024.1100.0.726
