### ISSUE TITLE
In-Game: repeat() loop counters have a 32bit Int overflow problem

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#8520]
### Description

So a few of us who didn't have anything better to do were taking a stroll through some of the generated YYC c++, and someone noticed something interesting.

![Image](https://github.com/user-attachments/assets/4060b413-1f69-4127-a308-dae6b5763e5f)

Oh dear, that doesn't look right.

This is because the generated c++ assigns the loop counter as a regular int, instead of an int64.

![Image](https://github.com/user-attachments/assets/dd50deaa-c9b4-4825-b4b2-357ab16e2142)

Manually editing the value to make it an int64 makes everything better.

![Image](https://github.com/user-attachments/assets/6012a692-aba3-44e2-a684-1b06c9b8f9bd)

Calling the repeat loop indirectly through a variable actually gets a little silly.

![Image](https://github.com/user-attachments/assets/1f1698ab-6f5c-4c97-9e55-990068540c2f)

Now the line needs a few corrections to function properly.

This is also an issue in VM, and while I obviously don't have access to the VM source code, I have a feeling it's doing something similar.

### Expected Change

integer overflows are usually bad

### Steps To Reproduce

  var t = int64(0);
  repeat (int64(5_000_000_000)) {
      t += int64(1);
  }
  show_debug_message(t);

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly), 2024.1100 (Betas)

### Which platform(s) are you seeing the problem on?

Windows

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2025.1 - if the compiler detects that expression on the repeat could be over 2Gb then it will use an int64 for the repeat - but this will not be full proof.

**Comment by sihammill** [comment]
The output value is still not correct in Beta IDE v2024.1300.0.721  Runtime v2024.1300.0.734

Using the original code shown in the report image as below results in : 705032704
```
var t = int64(0);
var n = 5_000_000_000;
repeat(n) {
t += int64(1);
}
show_debug_message(t);
```

Using the code in the repro steps also results in : 705032704
```
var t = int64(0);
repeat (int64(5_000_000_000)) {
t += int64(1);
}
show_debug_message(t);
```

**Comment by rwkay** [comment]
I am testing with  IDE v9.9.1.908  Runtime v9.9.1.1049 and it works fine....

**Comment by rwkay** [comment]
Unable to repro.

**Comment by DragoniteSpam** [comment]
russell you marked as fixed in november lol

**Comment by rwkay** [comment]
OK I have fixed both VM and HTML5 so they will work with stupidly large numbers...

**Comment by sihammill** [comment]
Fix verified in Beta IDE v2024.1300.0.726  Runtime v2024.1300.0.739
