### ISSUE TITLE
Code Editor 2: Color coding and collapsable text blocks broken

### ISSUE THREAD

**Issue by MangoB1** [YoYoGames/GameMaker-Bugs#9328]
### Description

CE2 colors and the areas that are supposedly collapsible are broken for one script (obj_player). Others are completely fine. Unsure how to replicate this. 

EDIT: Cutting and re-pasting the code again seems to temporarily resolve the issue for the original object however I have another script with an event that collides with obj_player and the colors and regions are still broken there. Cutting and pasting does not fix the issue.

![Image](https://github.com/user-attachments/assets/61cd857e-28fd-4c6a-a7f1-b02f8ac7ec7a)

https://api.gamemaker.io/api/github/downloads/6441fb4a-6719-4a70-9e06-148d371e3418

### Steps To Reproduce

1. Start GameMaker
2. Open up my obj_player script
3. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1300 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by MangoB1** [comment]
The issue is resolved for a duplicate object but issue still persists on the original game object.

**Comment by MangoB1** [comment]
Found a fix: I cut and pasted the code back and it has resolved the issue! Unsure how I can replicate the initial issue though.

**Comment by MangoB1** [comment]
Seems to persist in other game objects in my project as well but intermittently. I have to cut and paste the code for colors to restore and for the autocompletion feature to come back.

**Comment by zreedy** [comment]
Almost certainly fixed with https://github.com/YoYoGames/GameMaker-Bugs/issues/9312

**Comment by mgeddesGM** [comment]
original issue still present in  IDE v2024.1300.0.770  Runtime v2024.1300.0.777

the cut and repast seems to work but only for each event in obj_player

**Comment by zreedy** [comment]
Fixed. The issue is that there was an room instance renamed to `obj_player` which conflicted with the object asset name `obj_player`. The returned asset from `FindResourceByName` was the `GMRInstance` not the `GMObject`. I have changed the code to use a `FindPrimaryResourceByName` which defaults to the fast path and falls back to a slow path if the wrong asset type is discovered.

Room Instance Names should probably not be allowed to conflict with primary assets to prevent issues like this (I would not be surprised if there are other issues outside of Feather/CE2 that originate from the same issue). I asked internally and indeed this is documented and expected behavior relating to legacy functionality of Room Instances. As long as the name does not conflict in the locality of the room and its other resources, the identify is valid. This does mean that not only can room instance names conflict with primary assets, they can conflict with other rooms' Room Instance names.

**Comment by mgeddesGM** [comment]
verified in  IDE v2024.1300.0.775  Runtime v2024.1300.0.781 based on the above comment
